### ISSUE TITLE
2 Players spawn in Arena 2vs1, Your are in arena -1 with no opporent and Erros

### ISSUE THREAD

**Issue by stevemerson** [splewis/csgo-multi-1v1#100]
Hello i love this Plugin

So yesterday i have updatet the Server from 1.61 to 1.7.0 Sourcemod and the NEW version multi 1.0 from 0.5.2 and i have lot of bugs

First sometimes 2 players was in one arena 2vs1 
- sometimes dont have arena clantag and sometimes in chat was Your are in arena -1 with no opporent and we have players

Need help to fix the problems in error logs 

comes this errors:

L 03/15/2015 - 00:01:49: [multi1v1.smx] ♥Padziunia♥<1810><STEAM_1:0:90718970><> had arena -1 on player spawn event
L 03/15/2015 - 00:01:49: [SM] Plugin encountered error 15: Array index is out of bounds
L 03/15/2015 - 00:01:49: [SM] Displaying call stack trace for plugin "multi1v1.smx":
L 03/15/2015 - 00:01:49: [SM]   [0]  Line 141, ./scripting/multi1v1/natives.sp::Native_GetArenaPlayer1()
L 03/15/2015 - 00:01:49: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 03/15/2015 - 00:01:49: [SM] Native "Multi1v1_GetArenaPlayer1" reported: Arena -1 is not valid
L 03/15/2015 - 00:01:49: [SM] Displaying call stack trace for plugin "multi1v1_flashbangs.smx":
L 03/15/2015 - 00:01:49: [SM]   [0]  Line 55, ./scripting/multi1v1_flashbangs.sp::Multi1v1_AfterPlayerSpawn()
L 03/15/2015 - 00:02:09: [multi1v1.smx] Steven Douglas<1809><STEAM_1:0:35072428><> had arena -1 on player spawn event

Dont know what i can do to fix it please help me

Peace Steve MERSON

**Comment by splewis** [comment]
Can you list the other plugins running on your server? If another plugin is interfering with team changes, this can happen. Running ``sm plugins`` or ``sm plugins list`` should work.

**Comment by stevemerson** [comment]
"AbNeR ResetScore" (1.4) by AbNeR_CSS
 "Admin File Reader" (1.7.0-dev+5061) by AlliedModders LLC
 "Admin Help" (1.7.0-dev+5061) by AlliedModders LLC
 "AdminList" (1.0) by Runningcore
 "Admin Menu" (1.7.0-dev+5061) by AlliedModders LLC
 "Admin loggin" (1.0) by vIr-Dan
 "AFK Manager" (3.5.3) by Rothgar
 "Anti-Flood" (1.7.0-dev+5061) by AlliedModders LLC
 "R.K.C | AutoDownloader" (v1.0) by RoadSide Romeo
 "Auto-Inviter" (1.0) by Zephyrus 
"Basic Chat" (1.7.0-dev+5061) by AlliedModders LLC
 "Basic Comm Control" (1.7.0-dev+5061) by AlliedModders LLC
 "Basic Commands" (1.7.0-dev+5061) by AlliedModders LLC
 "Basic Info Triggers" (1.7.0-dev+5061) by AlliedModders LLC
 "Basic Votes" (1.7.0-dev+5061) by AlliedModders LLC
 "CallAdmin" (0.1.4) by Impact, Popoklopsi
 "CallAdmin: Ts3 module" (0.1.4) by Impact, Popoklopsi
 "CallAdmin UserManager" (0.1.4) by Popoklopsi, Impact
 "Chat Logger" (2.0) by McFlurry
 "Client Preferences" (1.7.0-dev+5061) by AlliedModders LLC
 "Cronjobs" (1.2) by Popoklopsi
 "[CSGO] Hs Impact Effect" (1.1) by TonyBaretta
 "[Source 2013] Custom Chat Colors" (3.1.0) by Dr. McKay
 "Fun Commands" (1.7.0-dev+5061) by AlliedModders LLC
 "Fun Votes" (1.7.0-dev+5061) by AlliedModders LLC
 "gameME Plugin" (4.4.2) by TTS Oetzel & Goerz GmbH
 "Hive365 Player" (3.0.2) by Hive365.co.uk
 "CS:GO Multi1v1" (1.0.0) by splewis
 "CS:GO Multi1v1: flashbangs addon" (1.0.0) by splewis
 "CS:GO Multi1v1: knife round addon" (1.0.0) by splewis
 "CS:GO Multi1v1: online stats viewer" (1.0.0) by splewis
 "Nextmap" (1.7.0-dev+5061) by AlliedModders LLC
 "OverCore Automatic Messages" (1.4) by ESK0
 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion
 "Player Commands" (1.7.0-dev+5061) by AlliedModders LLC
 "Players Votes" (1.5.0) by The Resident, pZv!
 "Quake Sounds v3" (3.4.2) by Spartan_C001
 "Reserved Slots" (1.7.0-dev+5061) by AlliedModders LLC
 "RoundEndSound" (1.0.0 beta4) by fluxX
 "Say Sounds (including Hybrid Edition)" (4.0.6) by Hell Phoenix|Naris|FernFerret|Uberman|psychonic|edgecom|woody|Miraculix|gH0sTy
 "SourceBans Checker" (SB-1.5.0F) by psychonic & Ca$h Munny, Sarabveer(VEER™)
 "Self-Mute" (1.0) by Otokiru
 "Server Hop" (0.8.2) by [GRAVE] rig0r
 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
 "SourceMod Anti-Cheat" (0.8.5.1) by SMAC Development Team
 "SMACBANS: Block" (0.2.0) by SMACBANS Team
 "SMAC Aimbot Detector" (0.8.5.1) by SMAC Development Team
 "SMAC Anti-Wallhack" (0.8.5.1) by SMAC Development Team
 "Knife Upgrade" (2.5.2) by Klexen
 "Sound Commands" (1.7.0-dev+5061) by AlliedModders LLC
 "SourceBans" (1.5.0F) by SourceBans Development Team, Sarabveer(VEER™)
 "SourceComms" (SB-1.5.0F) by Alex, Sarabveer(VEER™)
 "Spectate" (1.0) by Zipcore
 "Stamm Feature Chats" (1.3.1) by Popoklopsi
"Stamm Feature Chat Messages" (1.3.2) by Popoklopsi
 "Stamm Feature GrenadeTrail" (1.4.1) by Popoklopsi
 "Stamm Feature No Fall Damage" (1.2.1) by Popoklopsi
 "Stamm Feature PlayerTrail" (1.3.1) by Popoklopsi
 "Stamm Feature Show Damage" (1.3.1) by Popoklopsi
 "Stamm Feature VIP Slot" (1.3.1) by Popoklopsi
 "Stamm Feature VIP Tag" (1.4.2) by Popoklopsi
 "Stamm" (2.2.8) by Popoklopsi
 "sv_allow_votes_handler.smx" 
 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
 "Mapchooser Extended Sounds" (1.10.1) by Powerlord
 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
 "Rock The Vote" (1.6.3-dev+4598) by AlliedModders LLC
 "CallAdmin: Mysql module" (0.1.4) by Impact, Popoklopsi

That was all Plugins :))

**Comment by splewis** [comment]
Well, I have no idea what most of those do, so there's not much I can do. Try removing ones you don't actually need.

Pretty sure using
```
"Knife Upgrade" (2.5.2) by Klexen
```

will cause seemingly-random crashes, too.

**Comment by stevemerson** [comment]
Okay you think this plugin will be crash the Server ????

**Comment by stevemerson** [comment]
i will testing 1 day without the plugin
