### ISSUE TITLE
Add Natives to Set a players Arena & Opponent.

### ISSUE THREAD

**Issue by SM9MB** [splewis/csgo-multi-1v1#103]
Hello, I have been trying to code an addon for the 1v1 plugin but I can't possibly continue without these natives.

Thanks.

**Comment by splewis** [comment]
You can do that using the Multi1v1_OnPreArenaRankingsSet and Multi1v1_OnPostArenaRankingsSet forward by reordering the players.

**Comment by SM9MB** [comment]
Hi, if its not too much to ask, could you maybe show me an example? I have never dealt with forwards before.

Thanks

**Comment by SM9MB** [comment]
Nevermind, I have managed to get it working. Thanks so much ;)
