### ISSUE TITLE
sm_multi1v1_menu_open_behavior

### ISSUE THREAD

**Issue by keigel2001** [splewis/csgo-multi-1v1#104]
sm_multi1v1_menu_open_behavior "1" is bugged for me.
It still opens the menu sometimes. Not always, but sometimes...

SourceMod Version: 1.7.1-dev+5163
CS:GO Multi1v1 (1.0.1-dev): 53244d4ada222a22070b47291ce78c3cfa0f683c

**Comment by splewis** [comment]
I *think* I have fixed it. The issue had to do with prompting the menu before client cookies had ever been cached - so if the database was taking a while it would give the menu.

**Comment by keigel2001** [comment]
Finally had the time to test it.
It seems to work, thanks.
