### ISSUE TITLE
Plugins can't create .cfg files.

### ISSUE THREAD

**Issue by nguyenbaodanh** [splewis/csgo-multi-1v1#105]
Help can you upload all the .cfg of plugin ? idk why it can't create automatically on my linux server.
and it crash server continously

**Comment by nguyenbaodanh** [comment]
I also setup web > http://1hp-gaming.com/1v1/
but no stats there , maybe because no .cfg are created ?

**Comment by splewis** [comment]
1. then the server doesn't have write permissions in the cfg/sourcemod/multi1v1 directory
2. if it crashes remove other plugins extensions, there's nothing I can do to fix your crashes
3. you have to set ``sm_multi1v1_use_database`` to 1 and configure the ``multi1v1`` database

**Comment by nguyenbaodanh** [comment]
Thanks. working now
http://1hp-gaming.com/1v1/
but why there is nothing when I click on players name ? what should be there ?

**Comment by nguyenbaodanh** [comment]
I see here : http://csgo1v1.splewis.net/statistics

I want a stats site like your :( :+1:  so awesome

**Comment by supimfuzzy** [comment]
The player stats not showing up was due to serverid being always set to 0. I've made a pull request and you can download a clone after splewis merges it.
