### ISSUE TITLE
No stats in mysql database

### ISSUE THREAD

**Issue by justin2108** [splewis/csgo-multi-1v1#107]
~/addons/sourcemod/configs/databases.cfg
 - added the req table
mysql> desc multi1v1_stats
    -> ;
+--------------+-------------+------+-----+---------+-------+
| Field        | Type        | Null | Key | Default | Extra |
+--------------+-------------+------+-----+---------+-------+
| accountID    | int(11)     | NO   | PRI | 0       |       |
| serverID     | int(11)     | NO   |     | 0       |       |
| auth         | varchar(64) | YES  |     | NULL    |       |
| name         | varchar(64) | YES  |     | NULL    |       |
| wins         | int(11)     | YES  |     | 0       |       |
| losses       | int(11)     | YES  |     | 0       |       |
| rating       | float       | YES  |     | 1500    |       |
| lastTime     | int(11)     | YES  |     | 0       |       |
| recentRounds | int(11)     | YES  |     | 0       |       |
+--------------+-------------+------+-----+---------+-------+

the user has privileges to write and read in this table on all known connections.
but when users join there stats are not stored in the database.

am i missing something ?

**Comment by splewis** [comment]
Did you set ``sm_multi1v1_use_database`` to 1?

**Comment by justin2108** [comment]
] rcon sm_multi1v1_use_database
"sm_multi1v1_use_database" = "1" ( def. "0" )                                    - Whether a database is used to store player statistics

databases.cfg
        "multi1v1"
        {
                "driver"            "mysql"
                "host"              "localhost"   // localhost works too
                "database"          "sourcemod"
                "user"              "csgoserver"
                "pass"              "************"
                "timeout"           "10"
                "port"              "3306"  // whatever port MySQL is set up on, 3306 is default
        }

**Comment by justin2108** [comment]
it doesn't create the table either when i drop it.

**Comment by splewis** [comment]
Did you actually set sm_multi1v1_use_database in cfg/sourcemod/multi1v1/multi1v1.cfg and have you checked the error logs?

**Comment by justin2108** [comment]
it works now.

first i did was http://gaming.stackexchange.com/questions/172407/sourcebans-smx-database-failure-could-not-find-driver-mysql

then instead of localhost connect to 127.0.0.1
info: http://stackoverflow.com/questions/22436028/cant-connect-to-local-mysql-server-through-socket-tmp-mysql-sock-2

thx guys :D
