### ISSUE TITLE
I haven't multi1v1.cfg in the sourcemode folder

### ISSUE THREAD

**Issue by klykpl** [splewis/csgo-multi-1v1#108]
I haven't multi1v1.cfg in the sourcemode folder and i don't now what to do . Please help my

**Comment by splewis** [comment]
From the readme:

### Configuration

The file cfg/sourcemod/multi1v1/multi1v1.cfg will be autogenerated when the plugin is first run and you can tweak it if you wish.

Make sure you're looking in the right place, and that the server has write permissions to that directory.

**Comment by klykpl** [comment]
Im looking in the right place and i didn't see that and i run the server

**Comment by splewis** [comment]
Does the cfg/sourcemod/multi1v1 directory exist? If not you didn't install the plugin correctly.

**Comment by klykpl** [comment]
Yes i have correctly installed

**Comment by klykpl** [comment]
Can you help please ?

**Comment by splewis** [comment]
The only reason the file wouldn't be created would be the game server not having write permissions to that directory. Perhaps you uploaded the file as root but the server runs as another user?

**Comment by klykpl** [comment]
I don't now so what i must do ?

**Comment by splewis** [comment]
You should learn how user permissions work on your server.

**Comment by klykpl** [comment]
Now i have the plugin in the folder but when i write in console sm plugins list so they aren't why?

**Comment by klykpl** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/12066975/7284135/b78ef19e-e93b-11e4-99fc-ca3496e0349c.jpg)

**Comment by klykpl** [comment]
![2015-04-22_00001](https://cloud.githubusercontent.com/assets/12066975/7284170/e4cf890c-e93b-11e4-8d90-cb0d276a6c62.jpg)

**Comment by splewis** [comment]
If you actually read the output of ``sm plugins``, you would see it tells you to use ``sm plugins 11`` to see more plugins.
