### ISSUE TITLE
Doesn't show the plugin in the console

### ISSUE THREAD

**Issue by klykpl** [splewis/csgo-multi-1v1#109]
I have these files in the cfg / SourceMod / multi 1v1 
![bez tytulu](https://cloud.githubusercontent.com/assets/12066975/7284512/7e9880d2-e93e-11e4-99c9-8888e77f2dc7.jpg)
but when i write the command in the console "sm plugins list" does not show this plugin
![2015-04-22_00001](https://cloud.githubusercontent.com/assets/12066975/7284515/8fdcb516-e93e-11e4-858f-63e92df663a3.jpg)
Please Help my

**Comment by splewis** [comment]
I just told you in the other issue:

If you actually read the output of sm plugins, you would see it tells you to use sm plugins 11 to see more plugins.
