### ISSUE TITLE
I have a problem whit mysql

### ISSUE THREAD

**Issue by klykpl** [splewis/csgo-multi-1v1#110]
When i write in myqsl the code:
CREATE DATABASE game_servers_database;
CREATE USER 'mymulti1v1server'@'123.123.123.123' IDENTIFIED BY 'strongpassword';
GRANT ALL PRIVILEGES ON game_servers_database.multi1v1_stats TO 'mymulti1v1server'@'123.123.123.123';
FLUSH PRIVILEGES;

Whit correct user , password and host is a error 
![bez tytulu](https://cloud.githubusercontent.com/assets/12066975/7292526/13837040-e99d-11e4-9d96-b2b3bdcacfca.jpg)

**Comment by supimfuzzy** [comment]
You might have to create a database from your host's control panel.
