### ISSUE TITLE
Issues installing 1v1 game mode

### ISSUE THREAD

**Issue by iHateArrays** [splewis/csgo-multi-1v1#111]
We are trying to install the 1v1 server onto a server that already has pugsetup. Looking at the file directory compared to files mentioned in installation, as well as screen shots from other peoples issues, we seem to be missing files. One I noticed that I assume is important is multi1v1.cfg. When looking at all the files in the repo, I do not see this file, as well as addons/sourcemod/plugins/multi1v1.smx, addons/sourcemod/configs/multi1v1_weapons.cfg, and addons/sourcemod/translations. Which I can also not seem to find in the repo. Following is an image of our directory on the csgo server:
![Server Directory](http://i.imgur.com/SLGkAC6.png)

When we load the csgo server this is what initially shows, where you would then go to Exec CFG
![Initial options](http://i.imgur.com/iLca6Bh.jpg)

Which then brings us to 
![Next Menu](http://i.imgur.com/bz8DCQa.jpg)

This is the first time we have tried to set up a 1v1 server so any help would be appreciated!

**Comment by splewis** [comment]
Download a release. 

https://github.com/splewis/csgo-multi-1v1/releases/tag/v1.0.0

**Comment by iHateArrays** [comment]
Downloaded it do I put it in the servers cfg folder, or inside the
sourcemod folder

Thanks again

**Comment by iHateArrays** [comment]
![Current Directory](http://i.imgur.com/7UBbD3N.png)

to help

**Comment by splewis** [comment]
There's 2 directories in the release archive, one named ``addons`` and one named ``cfg``. You just merge those directories with the directories of the same name in the root ``csgo`` directory.

**Comment by iHateArrays** [comment]
Excellent, got it to work, thank you very much! Last question is are there
any  console/server commands associated with this gamemod, or is it all
done through the game cvar cfg file

Thanks again
Arrays

**Comment by nguyenbaodanh** [comment]
You can see any cvars or cmds of any plugins by using these commands in
console:
Sm plugins list // to see all plugins using on server
Then you will see the number berfore each plugins. For example #11 multi1v1
Now you can check all cvars and cmds by typing in server console
Sm plugins cvars 11
Sm plugins cmds 11

**Comment by splewis** [comment]
The readme describes some configuration options: 
https://github.com/splewis/csgo-multi-1v1#configuration
