### ISSUE TITLE
Custom rounds doesnt work for me

### ISSUE THREAD

**Issue by janssenb** [splewis/csgo-multi-1v1#112]
I tried the new Custom Rounds setup and enabled the "scout" round:

"CustomRoundTypes"
{
    "scout"
    {
        "name"      "Scout"
        "ranked"        "0"
        "optional"      "1"
        "enabled"       "1"
        "armor"     "1"
        "helmet"        "1"
        "weapons"
        {
            "weapon_knife"      ""
            "weapon_ssg08"      ""
        }
    }
}

but when the scout round comes neither me nor him  have any weapon or a knife.

(Build 74).

Cant find any errors in log files.

**Comment by splewis** [comment]
Thanks, should be fixed now.

**Comment by janssenb** [comment]
Now every Player gets two Scouts/Knife (one after another) and one is dropped at round start. Is this intended ? 

Thanks for you nice Plugin + work ! :+1:

**Comment by splewis** [comment]
Definitely not intended - I'll have to take another look.

**Comment by splewis** [comment]
Should be fixed now.

**Comment by janssenb** [comment]
Wow - you are fast. Will try tomorrow. 

Thanks !
