### ISSUE TITLE
multi1v1_cutstomrounds

### ISSUE THREAD

**Issue by ScarletGrey** [splewis/csgo-multi-1v1#113]
The multi1v1_customrounds.cfg file did not generate. Any ideas why?

**Comment by splewis** [comment]
Because it isn't supposed to "generate".

**Comment by ScarletGrey** [comment]
thats what i thought but i added it in and it isnt reading it. do i have to compile the generic.sp for it to work?

**Comment by splewis** [comment]
What version are you using?

**Comment by ScarletGrey** [comment]
1.0.0

**Comment by ScarletGrey** [comment]
ok gotcha thank you
