### ISSUE TITLE
The flashbang-plugin isn't working anymore

### ISSUE THREAD

**Issue by keigel2001** [splewis/csgo-multi-1v1#114]
I updated to latest commit(446cfdaab95512bcd3ec84c461216ae20d789b23) and replaced my old weapon rounds plugin with your new round types via a config file feature.

Noticing that the flashbang-plugin isn't working anymore (no errorlogs, plugin is loaded correctly).
It's just not giving any flashes when both player allows it (all roundtypes affected).

Metamod:Source Version 1.11.0-dev+985
SourceMod Version: 1.7.2-dev+5200

**Comment by splewis** [comment]
I know why. I'll try to fix it later today. The issue is the forward the flashbangs plugin is using - it needs to be a forward called after weapons are given, not just a post-spawn one.

**Comment by splewis** [comment]
This should be fixed now - only the multi1v1_flashbangs.smx file needs to be replaced (assuming you are using 1.0.1 already).

**Comment by keigel2001** [comment]
Yup, it's working.
Thanks for the fix :+1:
