### ISSUE TITLE
Error latest stable

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [splewis/csgo-multi-1v1#115]
Compiling multi1v1.sp ...
SourcePawn Compiler 1.8.0-dev+5552
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2015 AlliedModders LLC

/home/bcs/goarena1/csgo/addons/sourcemod/scripting/include/smlib/entities.inc(33) : error 138: const was specified twice
/home/bcs/goarena1/csgo/addons/sourcemod/scripting/include/smlib/crypt.inc(426) : error 173: 'in' is a newly reserved keyword that may be used in the future; use                             a different name as an identifier
/home/bcs/goarena1/csgo/addons/sourcemod/scripting/include/smlib/effects.inc(158) : warning 237: coercing functions to and from primitives is unsupported and wil                            l be removed in the future
include/multi1v1.inc(361) : error 008: must be a constant expression; assumed zero
include/logdebug.inc(62) : warning 234: symbol "FCVAR_PLUGIN" is marked as deprecated: No logic using this flag ever existed in a released game. It only ever app                            eared in the first hl2sdk.

multi1v1.sp(212) : warning 234: symbol "FCVAR_PLUGIN" is marked as deprecated: No logic using this flag ever existed in a released game. It only ever appeared in                             the first hl2sdk.

3 Errors.

**Comment by BrutalCSEjziponken** [comment]
Using sourcemod 1.8

**Comment by splewis** [comment]
I'm not going to fix sourcemod 1.8 compilation errors until sourcemod 1.8 is released. 

Also, I believe you're using an outdated version of smlib.
