### ISSUE TITLE
Error latest stable

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [splewis/csgo-multi-1v1#116]
Compiling multi1v1_flashbangs.sp ...
SourcePawn Compiler 1.8.0-dev+5552
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2015 AlliedModders LLC

include/multi1v1.inc(361) : error 008: must be a constant expression; assumed zero

1 Error.

**Comment by BrutalCSEjziponken** [comment]
Using sourcemod 1.8

**Comment by splewis** [comment]
See #115
