### ISSUE TITLE
Pointsystem standby

### ISSUE THREAD

**Issue by LordRofl** [splewis/csgo-multi-1v1#121]
When only 2 players on the server it can be frustrating for one player. He can easly loose 500 points ore more and no way out exept for disconnecting. Can you add a cvar to activate the pointsystem on x player like rankme/hlstatx?

**Comment by splewis** [comment]
That's really just a symptom of elo being a over-simplistic rating system. 

Regardless, I'd be fine with this added, but don't have time to add it myself. Probably needs an additional translation string telling uses why stats are disabled, too.
