### ISSUE TITLE
Only 2 players can play

### ISSUE THREAD

**Issue by madmate** [splewis/csgo-multi-1v1#123]
Only 2 people can play, all others only watching and become the message: "[Multi1v1] Sorry, all the arenas are currently full.".

**Comment by splewis** [comment]
What map are you seeing this on?

**Comment by madmate** [comment]
I tryed aim_deagle, aim_9h_ak and aim_map.

**Comment by splewis** [comment]
Those maps only have 1 arena, so only 2 players will be able to play.

See https://github.com/splewis/csgo-multi-1v1/blob/master/README.md#maps
