### ISSUE TITLE
sm_multi1v1_pistol_behavior 2 not working on rifle rounds

### ISSUE THREAD

**Issue by RavageCS** [splewis/csgo-multi-1v1#125]
sm_multi1v1_pistol_behavior 2 does not seem to work on rifle rounds. It gives the players choice of pistol not the sm_multi1v1_default_pistol.

It does give the sm_multi1v1_default_pistol on awp rounds

version 1.1.0-dev

**Comment by splewis** [comment]
This should be fixed now.

**Comment by RavageCS** [comment]
Many thanks to our supreme master coder
