### ISSUE TITLE
Why i have only one arena?.

### ISSUE THREAD

**Issue by hetmanpolska** [splewis/csgo-multi-1v1#137]
Hello, I do not know how to add more than one arena. I have a server 15 slotowy and would like to have these arenas 8, so everyone can play. Now on the server can be up to 8 people but that only one is operating. I would hope that all the work, I would ask for a quick answer as to add these 8 arenas :).

**Comment by HalfEatenPie** [comment]
Because the map you're using only has one arena.  

I'd suggest looking and making sure the map you're using actually has arenas and not just one "stage".

**Comment by hetmanpolska** [comment]
I use maps from other servers and there is always okay.

**Comment by splewis** [comment]
Link a map you're using that has this issue.

**Comment by hetmanpolska** [comment]
Because the map you're using only has one arena.

I'd suggest looking and making sure the map you're using actually has arenas and not just one "stage".

**Comment by hetmanpolska** [comment]
All the maps that I have uploaded to this problem. The problem lies not in the maps so I think.

**Comment by splewis** [comment]
Post the output of 
``sm plugins`` and check ``addons/sourcemod/logs`` for any error logs then.

**Comment by hetmanpolska** [comment]
Link to Errors :: http://www.speedyshare.com/yJJXZ/errors-20160103.log

**Comment by splewis** [comment]
Post the log, not a link to it.

**Comment by hetmanpolska** [comment]
L20160101.		01/01/16	21:27
		L20160102.log			02/01/16	22:10
		L20160103.log	  03/01/16	21:51
		errors_20160101.log		01/01/16	21:27
		errors_20160102.log		02/01/16	22:01
		errors_20160103.log

**Comment by hetmanpolska** [comment]
Which?

**Comment by HalfEatenPie** [comment]
I'd suggest you paste specific map links and/or paste the full log file into pastebin or paste.ee.  Not going to download the log file to open it locally.

**Comment by HalfEatenPie** [comment]
Also post the output of sm plugins.  There could also be a conflicting plugin involved

**Comment by hetmanpolska** [comment]
Errors: http://pastebin.com/vJjEJHqA
Maps: http://pastebin.com/DaPN4Biu

**Comment by splewis** [comment]
You're still yet to post the output of ``sm plugins list`` or the name of a map this occurs on.

**Comment by HalfEatenPie** [comment]
Like my original post said.  You're using the wrong maps.  

Your maps list says aim_map.  What this plugin uses is the am_ map varieties. 

When selecting maps to use for this plugin, please make sure it is the proper map made to be used with this plugin.  Just any random map does not work.

**Comment by hetmanpolska** [comment]
Tommorow i upload the am_maps. Thanks for help.
