### ISSUE TITLE
call stack trace ("m_fForceTeam" not found (entity 0/worldspawn))-error

### ISSUE THREAD

**Issue by keigel2001** [splewis/csgo-multi-1v1#139]
Not sure if you're already aware of this issue, but using the newest commit (b08a2e8195778f772689db91af5e1cf86c6b6f7a), I get some call stack trace errors multiple times per day (various maps):

> L 01/20/2016 - 17:49:45: SourceMod error session started
> L 01/20/2016 - 17:49:45: Info (map "am_aztec2014") (file "errors_20160120.log")
> L 01/20/2016 - 17:49:45: [SM] Native "SetEntPropFloat" reported: Property "m_fForceTeam" not found (entity 0/worldspawn)
> L 01/20/2016 - 17:49:45: [SM] Displaying call stack trace for plugin "multi1v1.smx":
> L 01/20/2016 - 17:49:45: [SM]   [0]  Line 431, multi1v1.sp::Event_OnFullConnect()
> L 01/20/2016 - 17:49:45: [SM] Native "SetEntPropFloat" reported: Property "m_fForceTeam" not found (entity 0/worldspawn)
> L 01/20/2016 - 17:49:45: [SM] Displaying call stack trace for plugin "multi1v1.smx":
> L 01/20/2016 - 17:49:45: [SM]   [0]  Line 431, multi1v1.sp::Event_OnFullConnect()
> L 01/20/2016 - 17:49:47: [SM] Native "SetEntPropFloat" reported: Property "m_fForceTeam" not found (entity 0/worldspawn)
> L 01/20/2016 - 17:49:47: [SM] Displaying call stack trace for plugin "multi1v1.smx":
> L 01/20/2016 - 17:49:47: [SM]   [0]  Line 431, multi1v1.sp::Event_OnFullConnect()
> L 01/20/2016 - 17:49:47: [SM] Native "SetEntPropFloat" reported: Property "m_fForceTeam" not found (entity 0/worldspawn)
> L 01/20/2016 - 17:49:47: [SM] Displaying call stack trace for plugin "multi1v1.smx":
> L 01/20/2016 - 17:49:47: [SM]   [0]  Line 431, multi1v1.sp::Event_OnFullConnect()
> L 01/20/2016 - 17:49:49: [SM] Native "SetEntPropFloat" reported: Property "m_fForceTeam" not found (entity 0/worldspawn)
> L 01/20/2016 - 17:49:49: [SM] Displaying call stack trace for plugin "multi1v1.smx":
> L 01/20/2016 - 17:49:49: [SM]   [0]  Line 431, multi1v1.sp::Event_OnFullConnect()
> L 01/20/2016 - 17:59:40: [SM] Native "SetEntPropFloat" reported: Property "m_fForceTeam" not found (entity 0/worldspawn)
> L 01/20/2016 - 17:59:40: [SM] Displaying call stack trace for plugin "multi1v1.smx":
> L 01/20/2016 - 17:59:40: [SM]   [0]  Line 431, multi1v1.sp::Event_OnFullConnect()
> L 01/20/2016 - 18:05:29: Error log file session closed.

Metamod:Source Version: 1.11.0-dev+998
SourceMod Version: 1.7.3-dev+5290

I don't think that I've conflicting plugins. Basically running this setup for 2 years now.
Thanks for your work :)

**Comment by splewis** [comment]
Is this issue new from the most recent update (Jan 20)?

**Comment by keigel2001** [comment]
No it isn't. I compiled it on Jan 18 and had the errors right away.
Using 85cf20b6cc2a660c8e2b5d4acdb0f5b06975e51c before (Dez 05) everything was working fine. Just upgraded because I was reinstalling all my servers and upgrading the sourcemod version.

**Comment by splewis** [comment]
I added a check to guard against this, but was unable to reproduce this. The error is mostly harmless, though.

**Comment by keigel2001** [comment]
Seems to work. No errors in days. Thx again :+1:
