### ISSUE TITLE
spawning in the middle of someones arena

### ISSUE THREAD

**Issue by gaming4keeps** [splewis/csgo-multi-1v1#141]
I have a bug where it takes players that have died in their arena, and spawns them in the middle of another 1v1 arena with a knife, while the arena is still active, as in, the two players are still trying to kill each other.

I have noticed it happening in a couple maps, one in particular am_quickdraw; if you kill you opponent, but then jump in the pit (which kills you) you respawn in the pit in another arena.

Any thoughts on why this is happening?

**Comment by splewis** [comment]
Do you have steps to reproduce this? (Including what version you're using)

**Comment by gaming4keeps** [comment]
yes. in am_quickdraw, with at least 4 players. jump in the pit and you are killed by environment and respawn in an active arena

do you want to jump in with us to see? you have to register first gamersaloon.com/csgo then choose the multi1v1 server.

**Comment by splewis** [comment]
It's most likely another plugin or config turning respawns on.

**Comment by gaming4keeps** [comment]
ok, ya i thought it might, ill look into that, thanks
