### ISSUE TITLE
How to use mutliple arenas

### ISSUE THREAD

**Issue by Angristan** [splewis/csgo-multi-1v1#142]
Hello,

Where do I put the list of the map I want to use with this plugin ?

**Comment by HalfEatenPie** [comment]
https://github.com/splewis/csgo-multi-1v1#maps

**Comment by Angristan** [comment]
It's not answering to my question :/

**Comment by HalfEatenPie** [comment]
Oops wrong link.

https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators

**Comment by Angristan** [comment]
So if I already use a map and a mapgroup from the workshop it's ok ?

**Comment by HalfEatenPie** [comment]
The plugin only sets up the cvars and game settings.  It doesn't handle the maplists or selects which map to load.  Therefore, if you already have it setup to use the multi-1v1 maps (prepended as am_ maps), then you're fine.

**Comment by Angristan** [comment]
Thank you !
