### ISSUE TITLE
Auto updater does not work

### ISSUE THREAD

**Issue by gaz492** [splewis/csgo-multi-1v1#143]
From what i could see the auto updater does not work.

I have the config option to use the auto updater set to 1 but if i do sm_updater_status it does not appear in the list.
Plugins being monitored for updates:
  [0]  updater.smx
  [1]  simple-chatprocessor.smx
Last update check was 1.5 minutes ago.
[Updater] --- Status End ---

and there are no errors in the sourcemod error logs

**Comment by HalfEatenPie** [comment]
What kind of a server are you running?  What OS? 

What do you get for sm_updater? 

Make sure you also have at least cURL, Socket, SteamTools, or SteamWorks installed.

**Comment by gaz492** [comment]
Im running a csgo multi1v1 server running on ubuntu 15.10 and i get "sm_updater" = "2" when running sm_updater running it with the latest socket

**Comment by splewis** [comment]
You have to set ``sm_multi1v1_autoupdate 1``.
