### ISSUE TITLE
Nextmap vote

### ISSUE THREAD

**Issue by jaccovdwijgaart** [splewis/csgo-multi-1v1#148]
Hi,

I am currently running this plugin on my server, i am hosting the maps from a workshop collection.
Now i have this problem that when the time expires (ca 11 minutes) there is no nextmap vote. please help me with this issue.

sorry for my english, it is not my main language.

**Comment by HalfEatenPie** [comment]
Check first by looking in your sourcemod plugins folder and seeing if nextmap or any of the other map control plugin is working.  I'd suggest disabling them to troubleshoot what the issue is.  From my experience, this plugin was not the cause of it.

**Comment by jaccovdwijgaart** [comment]
Hi,

i have copyd the server from my working 5v5 server which has the default end of map voting system that you would also have on like a mm casual server. should i use a custom end of map vote plugin? i am not fan of that and rather use the default one.

thank you for your commend!

**Comment by jaccovdwijgaart** [comment]
Should I use a custom end of map vote plugin? If so, how do input the workshop maps in?

**Comment by jaccovdwijgaart** [comment]
I think i have found why it doesn't work, the voting was disabled with the convar's of the plugin.
