### ISSUE TITLE
Server doesn´t load maps from the 1v1 collection

### ISSUE THREAD

**Issue by jnk88** [splewis/csgo-multi-1v1#149]
Hi,
I have a problem with the 1v1 plugin on my server. The plugin works very good, but only on the main csgo maps. So I tried the plugin on Dust2, it worked fine, but only for max 2 players. When I use the maps from the collection, the map doesn´t load and we can´t connect on the server. I have no idea how to fix this. 
Here I added my Server log (maybe it helps :))
Thanks for every answer and help.

[Server Log.txt](https://github.com/splewis/csgo-multi-1v1/files/206366/Server.Log.txt)

**Comment by splewis** [comment]
This plugin doesn't affect how your server loads maps. A better place to ask would be the general srcds on the alliedmodders forums.
