### ISSUE TITLE
[Request] Admin Only Spectate

### ISSUE THREAD

**Issue by Technoblazed** [splewis/csgo-multi-1v1#151]
I've tried to create my own plugin for this, and works fine on normal servers, however something appears to be conflicting within your plugin, so was wondering if this was something that could be implemented.

The main thing is to stop players from getting to Arena 1, joining spectate, then starting in Arena 10 or whatever again :D

**Comment by Headline22** [comment]
So you want to make it so when a player joins spec then when they join back they'll get sent to where they used to be?

**Comment by splewis** [comment]
I'd describe this as just ignoring teamjoin commands when: the arg is CS_TEAM_SPECTATOR, the player isn't an admin, and the plugin is enabled.
