### ISSUE TITLE
Next Map issue

### ISSUE THREAD

**Issue by IanCotrina** [splewis/csgo-multi-1v1#154]
When game finishes a vote starts for the next map, but they are not 1v1 maps, they are the default maps... However when i RTV it does shows the 1v1 maps
Pls help me :(

**Comment by splewis** [comment]
The multi1v1 plugin has nothing to do with your map voting/rotation system.

Your issue is probably that you're letting the built-in game voting system take effect, when you should be disabling it (since you're using the rtv + mapchooser plugins).

**Comment by splewis** [comment]
Closing since it's not multi1v1 related and there's no response.
