### ISSUE TITLE
!stats ingame not working

### ISSUE THREAD

**Issue by Brokolakis** [splewis/csgo-multi-1v1#155]
Hello,

When I type !stats on my server, nothing happens. My database and webstats are working -> http://bdoabout.com/srcweb/index.php

The Elosystem ingame is working too, but you cant use the command !stats or !rank.
!guns is working too. 

I hope somebody can help me.

- Plugin version: newest version
- Sourcemod version: newest version

**Comment by splewis** [comment]
Are you using the multi1v1_online_stats_viewer plugin? There is no sm_stats command in multi1v1 itself.

**Comment by Brokolakis** [comment]
This plugin is in my plugins folder, so yeah Im using this. This is the multi1v1_online_stats_viewer.cfg:

// This file was auto-generated by SourceMod (v1.8.0.5923)
// ConVars for plugin "multi1v1_online_stats_viewer.smx"


// Add up values to enable debug logging to those locations
//   1 = server console
//   2 = all clients' consoles
//   4 = consoles of admins with 'b' flag or access to 'sm_multi1v1_debug' override
//   8 = all clients' chat
//   16 = chat of admins with 'b' flag or acce
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "63.000000"
sm_multi1v1_debug "0"

// URL to send player stats to. You may use tags for userid and serverid via: {USER} and {SERVER}.  For example: http://bdoabout.com/srcweb/redirect.php.php?id={USER}&serverid={SERVER}.
// -
// Default: ""
sm_multi1v1_stats_url "http://bdoabout.com/srcweb/redirect.php?id={USER}"

// Top 15 URL. You may a tag for the serverid via: {SERVER}.  For example: http://bdoabout.com/srcweb/redirect.php?serverid={SERVER}.
// -
// Default: ""
sm_multi1v1_top_url "http://bdoabout.com/srcweb/redirect.php"

**Comment by Brokolakis** [comment]
I used before the example and had read somewhere that I dont need the server whem im using the webinterface. 

But "stats" it doesnt working, no response in console. If the database not working there will be a error I think.

**Comment by zAfLu** [comment]
Try !rank

**Comment by splewis** [comment]
sm_rank is the exact same as sm_stats.

@Brokolakis 

Trying your redirect.php pages (e.g. http://bdoabout.com/srcweb/redirect.php) in my browser does not work. I get a 403 forbidden response. Maybe permissions aren't set correctly?

**Comment by Brokolakis** [comment]
Youre right, but which permission are needed? I tried it witch chmod 777, but it doesnt working. Youre able to see index.php without special permission, why is redirect.php not working?

**Comment by Brokolakis** [comment]
I looked for this problem in www and found this thread "http://stackoverflow.com/questions/10873295/error-message-forbidden-you-dont-have-permission-to-access-on-this-server"

I tried this solution but it doesnt working, my standart config before I changed it was:

<Directory /var/www/vhosts/bdoabout.com/httpdocs>

		<IfModule mod_perl.c>
			<Files ~ (\.pl$)>
				SetHandler perl-script
				PerlHandler ModPerl::Registry
				Options +ExecCGI
				allow from all
				PerlSendHeader On
			</Files>
		</IfModule>
		<IfModule mod_python.c>
			<Files ~ (\.py$)>
				SetHandler python-program
				PythonHandler mod_python.cgihandler
			</Files>
		</IfModule>
		<IfModule mod_fcgid.c>
			<Files ~ (\.fcgi$)>
				SetHandler fcgid-script
				Options +ExecCGI
			</Files>
		</IfModule>
		<IfModule mod_fcgid.c>
			<Files ~ (\.php$)>
				SetHandler fcgid-script
				FCGIWrapper /var/www/cgi-bin/cgi_wrapper/cgi_wrapper .php
				Options +ExecCGI
			</Files>
		</IfModule>

		Options -Includes +ExecCGI

	</Directory>

May you know whats to do? Thanks you so much for your help!

**Comment by Brokolakis** [comment]
I checked now my .htaccess in main folder (htttpdocs), May I have to change something there?

I tried to change "Order deny,allow" to "Order Require all granted" but it doesnt working. I also added "AddHandler php-script .php" but it doesnt working too.. 

Heres the .htaccess file:

`<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^(downloads|keys|languages|stuff|template|third_party|tmp) - [F]
</IfModule>

<IfModule mod_rewrite.c>
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
</IfModule>

<IfVersion >= 2.4>
    <Files .htaccess>
        Require all denied
    </Files>
    <Files id_rsa>
       Require all denied
    </Files>
    <FilesMatch "\.pub$">
        Require all denied
    </FilesMatch>
    <FilesMatch "\.php$">
        Require all denied
    </FilesMatch>
    <FilesMatch "^(admin|ajax|api|cloud|get_password|images|index|install|jobs|lend|login|protectioncheck|reboot|serverallocation|startupdates|statuscheck|switch|update|userpanel)\.php$">
        Require all granted
    </FilesMatch>
</IfVersion>

<IfVersion < 2.4>
    <Files .htaccess>
        Order deny,allow
        deny from all
    </Files>
    <Files id_rsa>
        Order deny,allow
        deny from all
    </Files>
    <FilesMatch "\.pub$">
        Order deny,allow
        deny from all
    </FilesMatch>
    <FilesMatch "\.php$">
        Order deny,allow
        deny from all
    </FilesMatch>
    <FilesMatch "^(admin|ajax|api|cloud|get_password|images|index|install|jobs|lend|login|protectioncheck|reboot|serverallocation|startupdates|statuscheck|switch|update|userpanel)\.php$">
        Order allow,deny
        allow from all
    </FilesMatch>
</IfVersion>`

**Comment by Brokolakis** [comment]
Oh my god.. I got the solution "Order Require all granted" is false it have to be "Require all granted" :+1: 
Now its working, thank you for your help!

**Comment by Brokolakis** [comment]
I have one more question, which are all commands to use the statistic?

!rank
!stats
!top

Are they more commands?
