### ISSUE TITLE
Any method to disable the plugin temporarily through RCON?

### ISSUE THREAD

**Issue by TheSisb** [splewis/csgo-multi-1v1#157]
Not sure where else to ask - I set this up on my server and love it so far, but want to turn it off for scrims.  Couldn't find a command documented anywhere to toggle the plugin.  Any ideas? <3

**Comment by splewis** [comment]
sm_multi1v1_enabled 0

**Comment by TheSisb** [comment]
Haha just found the answer myself too.  Sorry for the bother and thanks!
