### ISSUE TITLE
Something haven't translation in txt

### ISSUE THREAD

**Issue by 872517414** [splewis/csgo-multi-1v1#158]
The Pistol Preference(4) and the Preference menu(3).
![8](https://cloud.githubusercontent.com/assets/9050713/19963721/a840905e-a1f8-11e6-9a4c-b1da78d2477d.png)
![9](https://cloud.githubusercontent.com/assets/9050713/19963734/b29caf38-a1f8-11e6-9e7a-bb9df8c50110.png)

**Comment by splewis** [comment]
The names are set from a config you can change: https://github.com/splewis/csgo-multi-1v1/blob/master/configs/multi1v1_weapons.cfg

Ideally the plugin would have the weapon names in translations, though (they might already exist in-game and could be reused, maybe), but I don't think that anyone is going to get around to that.

**Comment by 872517414** [comment]
OK.XD
