### ISSUE TITLE
Failed to auto generate config for multi1v1.smx

### ISSUE THREAD

**Issue by exxis** [splewis/csgo-multi-1v1#165]
i get following error message at the server startup

https://gyazo.com/53570fe7e5ca72c9255edac9ded7b641

i´ve running the csgo dedicated server on windows server 2016 i´ve checked the users write permissions and they are all correct. Don´t know how to fix this, hope someone can help here.

greets
exxis

**Comment by splewis** [comment]
https://forums.alliedmods.net/showpost.php?p=2502253&postcount=1246
