### ISSUE TITLE
Map change problem

### ISSUE THREAD

**Issue by wasyady** [splewis/csgo-multi-1v1#168]
**Don't change map (on Win 2008 R2), after 4/25/2017 CSGO update.**

The vote is done, but didn't change the map when the time is over.
Can't change the map with RCON or Sourcemod.
Without the plugin multi 1v1 working perfectly.

         Metamod:Source version 1.10.7-dev
         Built from: https://github.com/alliedmodders/metamod-source/commit/89c6fb3
         Build ID: 956:89c6fb3
         Loaded As: Valve Server Plugin
         Compiled on: Apr 26 2017
         Plugin interface version: 15:14
         SourceHook version: 5:5
         http://www.metamodsource.net/
		 
		 SourceMod Version Information:
         SourceMod Version: 1.8.0.5991
         SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5991)
         SourcePawn API: v1 = 4, v2 = 11
         Compiled on: Apr 29 2017 16:50:05
         Built from: https://github.com/alliedmodders/sourcemod/commit/b11c33c
         Build ID: 5991:b11c33c
         http://www.sourcemod.net/

           [SM] Listing 22 plugins:
           01 "Admin File Reader" (1.8.0.5991) by AlliedModders LLC
           02 "Admin Help" (1.8.0.5991) by AlliedModders LLC
           03 "Admin Menu" (1.8.0.5991) by AlliedModders LLC
           04 "Anti-Flood" (1.8.0.5991) by AlliedModders LLC
           05 "Basic Ban Commands" (1.8.0.5991) by AlliedModders LLC
           06 "Basic Chat" (1.8.0.5991) by AlliedModders LLC
           07 "Basic Comm Control" (1.8.0.5991) by AlliedModders LLC
           08 "Basic Commands" (1.8.0.5991) by AlliedModders LLC
           09 "Basic Info Triggers" (1.8.0.5991) by AlliedModders LLC
           10 "Basic Votes" (1.8.0.5991) by AlliedModders LLC
           11 "Client Preferences" (1.8.0.5991) by AlliedModders LLC
           12 "Fun Commands" (1.8.0.5991) by AlliedModders LLC
           13 "Fun Votes" (1.8.0.5991) by AlliedModders LLC
           14 "MapChooser" (1.8.0.5991) by AlliedModders LLC
           15 "CS:GO Multi1v1" (1.1.5) by splewis
           16 "Nextmap" (1.8.0.5991) by AlliedModders LLC
           17 "Map Nominations" (1.8.0.5991) by AlliedModders LLC
           18 "Player Commands" (1.8.0.5991) by AlliedModders LLC
           19 "RandomCycle" (1.8.0.5991) by AlliedModders LLC
           20 "Reserved Slots" (1.8.0.5991) by AlliedModders LLC
           21 "Rock The Vote" (1.8.0.5991) by AlliedModders LLC
           22 "Sound Commands" (1.8.0.5991) by AlliedModders LLC

**Comment by splewis** [comment]
"Can't change the map with RCON or Sourcemod." 

By this, do you mean:
- you start the server **with** multi1v1, type ``rcon changelevel am_grass2`` and nothing happens
- you start the server **without** multi1v1, type ``rcon changelevel am_grass2`` and it does change map

**Comment by wasyady** [comment]
Problem solved.

Sorry for the issue.
