### ISSUE TITLE
[GLOBAL ISSUE] after update no weapons other than knives

### ISSUE THREAD

**Issue by muffik9** [splewis/csgo-multi-1v1#170]
After the update by valve on 23rd of May 2017 all of the servers - and I mean all of them, have the same problem. The problem is that all of the players spawn only with knives, and no other weapon. This problem disregards all of the settings set by each player in the guns menu, so it s not due to all weapons being disabled automatically. 

Does anyone have any idea about what could be causing this problem ? If so, then maybe any idea how to fix this issue ?

Thanks in advance
Best Regards

**Comment by wasyady** [comment]
I find it everywhere.

[SM] Blaming: multi1v1.smx
[SM] Call stack trace:
[SM]   [0] CS_UpdateClientModel
[SM]   [1] Line 1034, D:\csgo\scripting\multi1v1.sp::SwitchPlayerTeam
[SM]   [2] Line 692, D:\csgo\scripting\multi1v1.sp::SetupPlayer
[SM]   [3] Line 628, D:\csgo\scripting\multi1v1.sp::Event_OnRoundPostStart

**Comment by wasyady** [comment]
New Sourcemod resolved my problem!

**Comment by splewis** [comment]
https://forums.alliedmods.net/showthread.php?t=297788
