### ISSUE TITLE
Top ui numbers not following actual rounds and k/d changing after a new round

### ISSUE THREAD

**Issue by olokos** [splewis/csgo-multi-1v1#173]
This is while playing 1v1

### Expected behavior
After won rounds, keep the numbers as they should be on top bar 
+
After 2 kills 1 death on 4th round keep 2 kills and 1 death

### Actual behavior
0:0 score after new round starts in top ui
+
1 kill 1 death only

### Steps to reproduce
Just go 1v1 with somebody else on the server.
- Plugin version: 1.1.5
- Sourcemod version:1.8.0.6009

**Comment by splewis** [comment]
I'm not sure I understand this.

It sounds like you're describing 2 separate issues:
1) The team scores not matching individual round wins when there are only 2 players in the server. That's not going to change.

2) The weird occurrences around score resets after the first round, which I think are the same as described in https://github.com/splewis/csgo-multi-1v1/issues/120

**Comment by olokos** [comment]
Correct, that's exactly what I meant.

1. Why isn't it going to change?
2.  Thanks.

**Comment by splewis** [comment]
I don't plan on manually setting team scores because I don't think it's a useful feature, and would require some bug-prone logic to make sure the scores are on the right teams as players could switch teams during it.

The plugin is not meant for a 2 player server.

**Comment by olokos** [comment]
I know it's not meant for 2 players, but sometimes people wanna 1v1 and I could setup a server by simply setting a password or changing playerlimit.

IMO a good solution would be to just make a trigger if 2 players on server -> keep teams if switch teams ->keep the scores as it was before switching teams.

**Comment by splewis** [comment]
The cost is in the writing and maintenance of the code. Detecting a "team switch" isn't entirely trivial with how the teams are managed in the plugin's internal priority queue in constructs each round. 

Sorry, this isn't a feature that's going to be added.
