### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by bcrivelaro** [splewis/csgo-multi-1v1#174]
When i try to compile, it gives me these errors:

> $ ./compile.sh multi1v1.sp 
> Compiling multi1v1.sp...
> SourcePawn Compiler 1.8.0.6015
> Copyright (c) 1997-2006 ITB CompuPhase
> Copyright (c) 2004-2015 AlliedModders LLC
> 
> /home/bruno/Downloads/sourcemod-1.8.0-git6015-linux/addons/sourcemod/scripting/include/smlib/entities.inc(33) : error 138: const was specified twice
> /home/bruno/Downloads/sourcemod-1.8.0-git6015-linux/addons/sourcemod/scripting/include/smlib/clients.inc(955) : warning 234: symbol "FindDataMapOffs" is marked as deprecated: Use FindDataMapInfo instead, or HasEntProp if you just want to check for existence.
> 
> /home/bruno/Downloads/sourcemod-1.8.0-git6015-linux/addons/sourcemod/scripting/include/smlib/clients.inc(1011) : warning 234: symbol "FindDataMapOffs" is marked as deprecated: Use FindDataMapInfo instead, or HasEntProp if you just want to check for existence.
> 
> /home/bruno/Downloads/sourcemod-1.8.0-git6015-linux/addons/sourcemod/scripting/include/smlib/clients.inc(1557) : warning 234: symbol "FindDataMapOffs" is marked as deprecated: Use FindDataMapInfo instead, or HasEntProp if you just want to check for existence.
> 
> /home/bruno/Downloads/sourcemod-1.8.0-git6015-linux/addons/sourcemod/scripting/include/smlib/crypt.inc(426) : error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as an identifier
> /home/bruno/Downloads/sourcemod-1.8.0-git6015-linux/addons/sourcemod/scripting/include/smlib/effects.inc(158) : warning 237: coercing functions to and from primitives is unsupported and will be removed in the future
> 
> 2 Errors.

Already tried with Sourcemod 1.7, already tried in Windows, already tried to change smlib version.

I'm currently using [0.11 version](https://github.com/bcserv/smlib/releases), the last one release. Any help?

**Comment by splewis** [comment]
The last release is very old, use the latest commit on github: https://github.com/bcserv/smlib

**Comment by bcrivelaro** [comment]
@splewis got it. Thanks man.
