### ISSUE TITLE
Players not receving weapons after new CS:GO update

### ISSUE THREAD

**Issue by J-Egebjerg** [splewis/csgo-multi-1v1#176]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Given weapons on spawn.

### Actual behavior
No weapons given on spawn.

### Steps to reproduce
- Plugin version: 1.1.5
- Sourcemod version: 1.8.0.6017
Join an am_ server and spawn in.
  
If you would like to test on my server - 185.121.173.218:27015  
Running no other addons.

**Comment by Technoblazed** [comment]
Update your gamedata to on your server. Restart your server twice, this will force a gamedata update and reload.
