### ISSUE TITLE
New Update broke the Plugin multi1vs1.smx

### ISSUE THREAD

**Issue by TandelK** [splewis/csgo-multi-1v1#177]
### Expected behavior
Should run properly on Server 

### Actual behavior
L 08/18/2017 - 18:27:05: Info (map "workshop/241267905/aim_multi_v4") (file "errors_20170818.log")
L 08/18/2017 - 18:27:05: [SM] Exception reported: Failed to locate function
L 08/18/2017 - 18:27:05: [SM] Blaming: multi1v1.smx
L 08/18/2017 - 18:27:05: [SM] Call stack trace:
L 08/18/2017 - 18:27:05: [SM]   [0] CS_SetClientClanTag
L 08/18/2017 - 18:27:05: [SM]   [1] Line 719, ./scripting/multi1v1.sp::SetupPlayer
L 08/18/2017 - 18:27:05: [SM]   [2] Line 628, ./scripting/multi1v1.sp::Event_OnRoundPostStart
Getting error in log file and server closing by itself.

### Steps to reproduce
- Plugin version:  1.1.4
- Sourcemod version: 1.8.0.6018

**Comment by Technoblazed** [comment]
Update your gamedata on your server. Restart your server twice, this will force a gamedata update and reload.
