### ISSUE TITLE
m_iWeaponID not found

### ISSUE THREAD

**Issue by Nachtfrische** [splewis/csgo-multi-1v1#179]
Hello, even after upgrading to newest version 1.1.6, which should fix this bug in theory, I'm still getting this error in my logs.

```
L 08/20/2017 - 15:36:04: [SM] Exception reported: Temp entity property "m_iWeaponID" not found
L 08/20/2017 - 15:36:04: [SM] Blaming: multi1v1.smx
L 08/20/2017 - 15:36:04: [SM] Call stack trace:
L 08/20/2017 - 15:36:04: [SM]   [0] TE_ReadNum
L 08/20/2017 - 15:36:04: [SM]   [1] Line 63, ./scripting/multi1v1/mute.sp::Hook_ShotgunShot
```

So that didn't fix the issue for me.

**Comment by splewis** [comment]
1.1.7 should work: https://github.com/splewis/csgo-multi-1v1/releases/tag/1.1.7

**Comment by Nachtfrische** [comment]
I can confirm, that this has fixed the issue for me, thank you!
