### ISSUE TITLE
1v1 help

### ISSUE THREAD

**Issue by barankx** [splewis/csgo-multi-1v1#182]
i want to use this plugin on custom map how can i set this to that? or maybe how can i open close this plugin?

**Comment by splewis** [comment]
I don't understand your question.

>  i set this to that

What is 'this' and what is 'that'?

> or maybe how can i open close this plugin?

I don't know what you mean either. There's a ``sm_multi1v1_enabled`` cvar you can set to enable/disable the plugin.
