### ISSUE TITLE
Don't save guns choose in cookie

### ISSUE THREAD

**Issue by rsgua** [splewis/csgo-multi-1v1#186]
Don't save guns choose in cookie. And clear server only with multy 1v1 and standard sourcemod plugins don`t save.
- Plugin version: latest
- Sourcemod version: latest

**Comment by splewis** [comment]
Can you provide actual version numbers?

**Comment by rsgua** [comment]
sm: 1.8.0.6027
Filename: am/multi1v1.smx
           Title: CS:GO Multi1v1 (Multi-arena 1v1 laddering)
           Author: splewis
           Version: 1.1.7
           URL: https://github.com/splewis/csgo-multi-1v1
           Status: running
           Timestamp: 10/24/2017 14:56:52
           Hash: 30ad60916701822b2a77a8b473e052d1

**Comment by InvexByte** [comment]
@rsgua Are you by any chance using GOTV? For spectating or to record demos?

Check `tv_enable 1`?
I have a problem related to GOTV and multi1v1 with cookies, may be same as yours.

**Comment by splewis** [comment]
https://forums.alliedmods.net/showpost.php?p=2562433&postcount=10

**Comment by OkyHp** [comment]
Faced with the same problem. I tried to put the version before the change, unfortunately did not help. Also, there is no possibility to check the work GO TV (After the last update the game crash the server if `tv_enable 0`).
If you need any information please let us know.
**Information:**
`SourceMod: 1.8.0.6036`
`Filename: arena/multi1v1.smx `
`Title: CS:GO Multi1v1 (Multi-arena 1v1 laddering) `
`Author: splewis `
`Version: 1.1.8-dev ( #185 )`
`URL: https://github.com/splewis/csgo-multi-1v1 `
`Status: running `
`Timestamp: 12/06/2017 01:29:00 `
`Hash: 56396e4e5318c6083bb53d9a079b2448 `

**Comment by InvexByte** [comment]
I'm managed to fix this.
Tested and works for multiple days now.

I just ended up doing what KyleS suggested here:
https://github.com/alliedmodders/sourcemod/issues/726

By making sure the cookies are all made **OnPluginStart().**

Added to end of **OnPluginStart()**:
```
    CloseHandle(FindNamedCookie("multi1v1_allowrifle"));
    CloseHandle(FindNamedCookie("multi1v1_allowpistol"));
    CloseHandle(FindNamedCookie("multi1v1_allowawp"));
    CloseHandle(FindNamedCookie("multi1v1_allowawpnopistols"));
    CloseHandle(FindNamedCookie("multi1v1_allowdeagle"));
    CloseHandle(FindNamedCookie("multi1v1_allowscout"));
    CloseHandle(FindNamedCookie("multi1v1_allowknife"));
    CloseHandle(FindNamedCookie("multi1v1_allowzeus"));
    CloseHandle(FindNamedCookie("multi1v1_allowheadshot"));
    CloseHandle(FindNamedCookie("multi1v1_rifle"));
    CloseHandle(FindNamedCookie("multi1v1_pistol"));
    CloseHandle(FindNamedCookie("multi1v1_preference"));
```

Its kinda ugly but could be pushed to master.
Thoughts @splewis?

These changes can (and should) be reverted as it doesn't change anything: f59490e

**Comment by splewis** [comment]
I have a plan to fix this properly shortly.

One side effect will be that the ``Multi1v1_OnRoundTypesAdded`` forward and the reading of the custom rounds config file will **only** happen on plugin start - not every map change. 

I don't see that being a problem for most users, but it might surprise some. If someone uses different round types per-map, they should change that to enabling/disabling them selectively via ``Multi1v1_DisableRoundType`` and ``Multi1v1_EnableRoundType``.

**Comment by splewis** [comment]
I've made some changes in 9c074c9abc17030171651a08022ea8f427307152 that should fix this as I described above. Testing would be appreciated.

**Comment by InvexByte** [comment]
Sweet testing now on my servers. Should have conclusive answers within 24 hours.

**Comment by InvexByte** [comment]
@splewis Yeah it works fine. Good work 👍

**Comment by splewis** [comment]
So I think this is resolved... closing. Thanks for the debugging work.
