### ISSUE TITLE
1v1 for sourcemod 1.8

### ISSUE THREAD

**Issue by MiisterChips** [splewis/csgo-multi-1v1#192]
Hi, I do not arrive has to install the mod for sourcemod 1.8 and I saw that to specify you only for sourcemod 1.7"but I do not arrive has to install sourcemode 1.7 on my waiter (Linux)

**Comment by splewis** [comment]
Sourcemod 1.8 will work fine. I updated the readme.

**Comment by wasyady** [comment]
Dosen't work special rounds with newest version. (on Win neither)
@MiisterChips  Use the previus version (1.1.7) and It will work perfectly!
