### ISSUE TITLE
Request: randomize the spawn location of players

### ISSUE THREAD

**Issue by k4tyxd** [splewis/csgo-multi-1v1#194]
So I've been an avid user of this, and the problem is that because the user spawn points are allocated as a part of map data,
if you play the game long enough, you start to know where people will spawn. I was wondering is there anyway to completely
randomize the spawn location of players using external plugins?

**Comment by splewis** [comment]
I'm not going to add any more randomization than what the plugin already supports (where it randomly chooses between any of the spawns in the arena).

I don't really know what "completely randomize" the spawn location means, but you can absolutely do whatever you want in another external plugin.
