### ISSUE TITLE
How to add slot map am_xxx ?

### ISSUE THREAD

**Issue by ThanhByKyTa** [splewis/csgo-multi-1v1#198]
![image](https://user-images.githubusercontent.com/33537916/39396340-a8cd5a84-4b16-11e8-9f57-711ee6f90985.png)

**Comment by splewis** [comment]
You edit the map in hammer.

https://github.com/splewis/csgo-multi-1v1#maps

Search for hammer tutorials if you want help. It's unrelated to the plugin.
