### ISSUE TITLE
getting this

### ISSUE THREAD

**Issue by rpkaul** [splewis/csgo-multi-1v1#199]
L 05/01/2018 - 18:40:10: [SM] Exception reported: Failed to locate function
L 05/01/2018 - 18:40:10: [SM] Blaming: multi1v1.smx
L 05/01/2018 - 18:40:10: [SM] Call stack trace:
L 05/01/2018 - 18:40:10: [SM]   [0] CS_UpdateClientModel
L 05/01/2018 - 18:40:10: [SM]   [1] Line 1096, ./scripting/multi1v1.sp::SwitchPlayerTeam
L 05/01/2018 - 18:40:10: [SM]   [2] Line 755, ./scripting/multi1v1.sp::SetupPlayer
L 05/01/2018 - 18:40:10: [SM]   [3] Line 690, ./scripting/multi1v1.sp::Event_OnRoundPostStart

**not able to join T side**

**Comment by splewis** [comment]
You have out of date sourcemod gamedata. Not a multi1v1 issue.

You should try updating sourcemod and then restarting your server so the gamedata updates.
