### ISSUE TITLE
How fix this ?

### ISSUE THREAD

**Issue by ThanhByKyTa** [splewis/csgo-multi-1v1#203]
![image](https://user-images.githubusercontent.com/33537916/44626513-e6844380-a947-11e8-81de-a2fdb716b5c2.png)

**Comment by splewis** [comment]
Sounds like the same bug as https://github.com/splewis/csgo-multi-1v1/issues/140

You could restart your server more often as a workaround. Seeing that the bug report is 2.5 years old I wouldn't expect it to get fixed too soon.
