### ISSUE TITLE
SQL Error Multi1v1

### ISSUE THREAD

**Issue by freakav** [splewis/csgo-multi-1v1#204]
Does someone know what is this error to solve it ? 

L 08/27/2018 - 09:05:38: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xD1\x84\xD0\xB5\xD0\xBF...' for column 'name' at row 1
L 08/27/2018 - 09:08:41: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xF0\x9F\x91\x91Ze...' for column 'name' at row 1
L 08/27/2018 - 09:10:52: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xE2\x98\x86P3N...' for column 'name' at row 1
L 08/27/2018 - 09:13:44: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xE2\x98\xAFPan...' for column 'name' at row 1
L 08/27/2018 - 09:15:23: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xC8\x98aKaL...' for column 'name' at row 1
L 08/27/2018 - 09:16:02: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xE2\x9C\xAAHer...' for column 'name' at row 1
L 08/27/2018 - 09:19:31: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xEF\xBD\xAF' for column 'name' at row 1

**Comment by ipsingh06** [comment]
I see this error for players that have unicode characters in their names. If you remove the unicode characters the error goes away.

**Comment by splewis** [comment]
Same as https://github.com/splewis/csgo-multi-1v1/issues/99.
