### ISSUE TITLE
Crashing After Update

### ISSUE THREAD

**Issue by ThanhByKyTa** [splewis/csgo-multi-1v1#205]
Can you update or fix multi1v1.smx ?
When i join CT or T = Crash

**Comment by supaflybanzai** [comment]
same

**Comment by killerbigpoint** [comment]
I'm in the middle of finding out why, will post a working .smx if i ever get it to work :P

**Comment by baferpro** [comment]
https://hlmod.ru/threads/proizvolnyj-vylet-servera-posle-obnovlenija-04-10-2018.46291/page-2#post-376908
Temporary fix

**Comment by Xatenev** [comment]
@baferpro Can you edit your comment with a translation for the non-russian people?

**Comment by baferpro** [comment]
@Xatenev Unfortunately not, that comment is not mine.
Yes, and there is nothing to read. Just download the archive and upload it to the server.

**Comment by klajdi369** [comment]
I cant seem to download the file, is there any other place to get it?

**Comment by baferpro** [comment]
[game.cstrike.ext.2.csgo.zip](https://github.com/splewis/csgo-multi-1v1/files/2447451/game.cstrike.ext.2.csgo.zip)

**Comment by ipsingh06** [comment]
I can confirm that the latest dev build of Sourcemod v1.10.6339 fixes the crash.

**Comment by ThanhByKyTa** [comment]
1.9 - build 6254. It fix crash ???

**Comment by versedispersed** [comment]
It has been said that updating sourcemod to 1.10 fixes the issue
Mentioned here: https://forums.alliedmods.net/showthread.php?t=241056&highlight=csgo+multi+1v1&page=147
Sourcemod dev releases (where 1.10 is): https://www.sourcemod.net/downloads.php?branch=dev

**Comment by versedispersed** [comment]
Plugin won’t work on 1.9 though. :(
		
		

		Have a great day,
Michael
	




On Thu, Oct 4, 2018 at 7:27 PM -0700, "Sean Lewis" <notifications@github.com> wrote:












This isn't a plugin issue. It's a sourcemod issue.


alliedmodders/sourcemod#893 looked to fix it. If you have crashes, get a newer soucemod build from 1.9 or 1.10. 1.10 is unstable, so I suggest sticking to 1.9.

**Comment by versedispersed** [comment]
The plugin won’t work on 1.9 though. Quick question: how can I get the game info of my server to display normally? What I mean is: When viewing the server in the server browser, I see Max Players 32 and the amount of time the server has been up.

**Comment by versedispersed** [comment]
Also, NuclearFalloit said that disabling bots should resolve the issue as well if still on the SM that keeps crashing servers.

**Comment by ThanhByKyTa** [comment]
I update 1.9 - build 6254 and fix crash !

**Comment by klajdi369** [comment]
Is it only me, or people experiencing crashes when choosing a team?

**Comment by AkalaGit** [comment]
I was having the same crash issue. Re-installed Sourcemod 1.9 to my server (at the moment this is the current version) and now the server works w/o any issues.
