### ISSUE TITLE
 Exception reported: Failed to lookup SetClanTag signature

### ISSUE THREAD

**Issue by ThanhByKyTa** [splewis/csgo-multi-1v1#207]
Today csgo update and plugin multi1v1.smx can't run.
File LOG
L 10/10/2018 - 09:37:14: [SM] Exception reported: Failed to lookup SetClanTag signature.
L 10/10/2018 - 09:37:14: [SM] Blaming: multi1v1\multi1v1.smx
L 10/10/2018 - 09:37:14: [SM] Call stack trace:
L 10/10/2018 - 09:37:14: [SM]   [0] CS_SetClientClanTag
L 10/10/2018 - 09:37:14: [SM]   [1] Line 785, multi1v1.sp::SetupPlayer
L 10/10/2018 - 09:37:14: [SM]   [2] Line 693, multi1v1.sp::Event_OnRoundPostStart

**Comment by splewis** [comment]
Sourcemod issue. Update your gamedata.

https://github.com/splewis/csgo-pug-setup/wiki/Frequently-Asked-Questions#issues-after-a-csgo-update-aka-help-a-csgo-update-broke-the-mod

**Comment by ThanhByKyTa** [comment]
ok this working 
Thanks @splewis
