### ISSUE TITLE
11/5/2018 after valve release note issue

### ISSUE THREAD

**Issue by Artinovich** [splewis/csgo-multi-1v1#208]
L 11/06/2018 - 17:54:35: [SM] Exception reported: Failed to lookup SetClanTag signature.
L 11/06/2018 - 17:54:35: [SM] Blaming: multi1v1.smx
L 11/06/2018 - 17:54:35: [SM] Call stack trace:
L 11/06/2018 - 17:54:35: [SM]   [0] CS_SetClientClanTag
L 11/06/2018 - 17:54:35: [SM]   [1] Line 785, ./scripting/multi1v1.sp::SetupPlayer
L 11/06/2018 - 17:54:35: [SM]   [2] Line 693, ./scripting/multi1v1.sp::Event_OnRoundPostStart

Windows machine
both sourcemod and metamod updated to latest stable build
plugin is latest version on github

After last update from valve , one player is able to join the server , and others sitting in spectate nothing is loading
any help

**Comment by splewis** [comment]
It's a sourcemod issue.

Wait for https://github.com/alliedmodders/sourcemod/pull/922 to be resolved. 

Until then you can try to set ``sm_multi1v1_use_team_tags 0`` as a workaround.
