### ISSUE TITLE
Joining team [on Win]

### ISSUE THREAD

**Issue by wasyady** [splewis/csgo-multi-1v1#209]
I had a problem after today's update.
Player's can't join any team.

Win Server 2008  R2 64bit
Source version 1.11.0-dev+1107
SourceMod Version: 1.9.0.6260

[SM] Listing 17 plugins:
           01 "Admin File Reader" (1.9.0.6260) by AlliedModders LLC
           02 "Admin Help" (1.9.0.6260) by AlliedModders LLC
           03 "Admin Menu" (1.9.0.6260) by AlliedModders LLC
           04 "Anti-Flood" (1.9.0.6260) by AlliedModders LLC
           05 "Basic Chat" (1.9.0.6260) by AlliedModders LLC
           06 "Basic Comm Control" (1.9.0.6260) by AlliedModders LLC
           07 "Basic Commands" (1.9.0.6260) by AlliedModders LLC
           08 "Basic Info Triggers" (1.9.0.6260) by AlliedModders LLC
           09 "Basic Votes" (1.9.0.6260) by AlliedModders LLC
           10 "Client Preferences" (1.9.0.6260) by AlliedModders LLC
           11 "Fun Commands" (1.9.0.6260) by AlliedModders LLC
           12 "Fun Votes" (1.9.0.6260) by AlliedModders LLC
           13 "CS:GO Multi1v1" (1.1.9) by splewis
           14 "Nextmap" (1.9.0.6260) by AlliedModders LLC
           15 "Player Commands" (1.9.0.6260) by AlliedModders LLC
           16 "Reserved Slots" (1.9.0.6260) by AlliedModders LLC
           17 "Sound Commands" (1.9.0.6260) by AlliedModders LLC

Error in log:
L 11/06/2018 - 18:55:31: SourceMod error session started
L 11/06/2018 - 18:55:31: Info (map "workshop/280544066/am_dust2") (file "errors_20181106.log")
L 11/06/2018 - 18:55:31: [SM] Exception reported: Failed to lookup SetClanTag signature.
L 11/06/2018 - 18:55:31: [SM] Blaming: multi1v1.smx
L 11/06/2018 - 18:55:31: [SM] Call stack trace:
L 11/06/2018 - 18:55:31: [SM]   [0] CS_SetClientClanTag
L 11/06/2018 - 18:55:31: [SM]   [1] Line 785, ./scripting/multi1v1.sp::SetupPlayer
L 11/06/2018 - 18:55:31: [SM]   [2] Line 693, ./scripting/multi1v1.sp::Event_OnRoundPostStart
L 11/06/2018 - 18:55:38: [SM] Exception reported: Failed to lookup SetClanTag signature.
L 11/06/2018 - 18:55:38: [SM] Blaming: multi1v1.smx
L 11/06/2018 - 18:55:38: [SM] Call stack trace:
L 11/06/2018 - 18:55:38: [SM]   [0] CS_SetClientClanTag
L 11/06/2018 - 18:55:38: [SM]   [1] Line 1005, ./scripting/multi1v1.sp::Command_JoinTeam

Thank you in advance for your help!

**Comment by splewis** [comment]
It's a sourcemod issue.

Wait for https://github.com/alliedmodders/sourcemod/pull/922 to be resolved. 

Until then you can try to set ``sm_multi1v1_use_team_tags 0`` as a workaround.
