### ISSUE TITLE
Appeared strange bugs

### ISSUE THREAD

**Issue by T1MOXA** [splewis/csgo-multi-1v1#214]
![image](https://user-images.githubusercontent.com/19938629/50042071-4b82b700-0067-11e9-885c-b638182c12e9.png)
In addition, for some reason, the warm-up at the beginning of the map is turned on.

- Plugin version: 1.1.10-dev
- Sourcemod version: 1.10.0.6362

**Comment by ThanhByKyTa** [comment]
@T1MOXA using mp_warmup 0

**Comment by T1MOXA** [comment]
@ThanhByKyTa Unknown command "mp_warmup"
The value of the mp_warmuptime variable itself changes to 300 for some reason.

**Comment by ThanhByKyTa** [comment]
@T1MOXA I think plugin set warmup :)

**Comment by splewis** [comment]
I'm closing this unless you can give specific steps to reproduce your issues. The original form asks for:
```
- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):
```

for a reason.
