### ISSUE TITLE
usp-s to p2000

### ISSUE THREAD

**Issue by dzagu** [splewis/csgo-multi-1v1#215]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Actual behavior
When some users taking usp-s server changing this for p2000. 

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: 1.19
- Sourcemod version: newest stable
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Known issue: https://github.com/splewis/csgo-multi-1v1/issues/8
