### ISSUE TITLE
Disable rounds, team switching messes up scoring

### ISSUE THREAD

**Issue by rawsh** [splewis/csgo-multi-1v1#217]
I'd like to disable awp, pistol, and rifle rounds and only use my custom deagle round.

- When a round is over, teams are switched but scoring is not. Ended with 27 mvps on one side and 23 on the other but the score was 28-29.

- When the game was over it went to dust2, not the other maps in collection. (probably my fault)

Thanks!

**Comment by splewis** [comment]
> I'd like to disable awp, pistol, and rifle rounds and only use my custom deagle round.

You have to write another plugin doing that using https://github.com/splewis/csgo-multi-1v1#adding-round-types-via-another-plugin

> When a round is over, teams are switched but scoring is not. Ended with 27 mvps on one side and 23 on the other but the score was 28-29.

The team scores are not intended to be accurate. 

> When the game was over it went to dust2, not the other maps in collection. (probably my fault)

How your server changes maps is totally unrelated to the multi1v1 plugin.
