### ISSUE TITLE
the plugin is broken he spawning 4 players on one arena or sometime you cant even see the player that  same arena with you

### ISSUE THREAD

**Issue by gal985** [splewis/csgo-multi-1v1#218]
when there is 4 players or more most of the time the plugin should put 2 players per arena but now
he sometime putting like 4 players on the same arena or sometimes he even just saying on Scoreboard  that lets say me and my friend on arena 2 but I can't see him seems that he teleport him to some other arena then arena 2 

- Plugin version:1.1.9
- Sourcemod version:1.9.6273
- Steps to reproduce (please be specific):
when more than 2 players join the plugin will not give them arena he will just put them on the same arena 
 I think the last update broke the plugin it's unplayable 
please fix that

**Comment by borzaka** [comment]
I just played on a server with these plugin versions, and no problem.
SourceMod 1.9.0.6267, by AlliedModders LLC
"CS:GO Multi1v1" (1.1.7) by splewis

**Comment by splewis** [comment]
Without a map to reproduce on this isn't enough information.
