### ISSUE TITLE
Players spawning on same team, no weapons given

### ISSUE THREAD

**Issue by Software-Noob** [splewis/csgo-multi-1v1#219]
### Expected behavior
Players face each other one by one with their selected weapons.

### Actual behavior
Players keep being spawned in the same team, random arenas and don't receive weapons. This does not happen constantly, but very often and makes 1v1 arena unplayable.

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: CS:GO Multi1v1" (1.1.9) by splewis
- Sourcemod version: 1.9.0.6275
- Steps to reproduce (please be specific):
Get on the server with 2-4 people playing in the arena and this will occur every map.

Constantly same error in log over and over:

```
L 01/22/2019 - 22:10:19: [SM] Exception reported: Plugin handle 550054 is invalid (error 1)
L 01/22/2019 - 22:10:19: [SM] Blaming: multi1v1.smx
L 01/22/2019 - 22:10:19: [SM] Call stack trace:
L 01/22/2019 - 22:10:19: [SM]   [0] Call_StartFunction
L 01/22/2019 - 22:10:19: [SM]   [1] Line 199, ./scripting/multi1v1/natives.sp::Native_GivePlayerArenaWeapons
L 01/22/2019 - 22:10:19: [SM]   [3] Multi1v1_GivePlayerArenaWeapons
L 01/22/2019 - 22:10:19: [SM]   [4] Line 794, ./scripting/multi1v1.sp::SetupPlayer
L 01/22/2019 - 22:10:19: [SM]   [5] Line 693, ./scripting/multi1v1.sp::Event_OnRoundPostStart
```

**Comment by m0rbit** [comment]
support! Same problem! Players appear in each other

**Comment by paulocrash** [comment]
I have the same problem:
```
L 10/25/2019 - 16:51:17: [SM] Exception reported: Plugin handle 5b005b is invalid (error 1)
L 10/25/2019 - 16:51:17: [SM] Blaming: multi1v1.smx
L 10/25/2019 - 16:51:17: [SM] Call stack trace:
L 10/25/2019 - 16:51:17: [SM]   [0] Call_StartFunction
L 10/25/2019 - 16:51:17: [SM]   [1] Line 199, ./scripting/multi1v1/natives.sp::Native_GivePlayerArenaWeapons
L 10/25/2019 - 16:51:17: [SM]   [3] Multi1v1_GivePlayerArenaWeapons
L 10/25/2019 - 16:51:17: [SM]   [4] Line 791, ./scripting/multi1v1.sp::SetupPlayer
L 10/25/2019 - 16:51:17: [SM]   [5] Line 690, ./scripting/multi1v1.sp::Event_OnRoundPostStart
```
I'm using **Sourcemod v1.10 - build 6453**

Any @splewis solutions? 

This problem started happening to me this week, the only major change I made on the server was to upgrade SourceMod & Metamod to the latest stable release v1.10.

**Comment by iGreen123** [comment]
any solution?

**Comment by crashzk** [comment]
I've been watching this error, from what I've seen it happens on maps that don't have support for so many players / arenas.

That is, your server is 32 slots, you put a map for 16 arenas / 32 players in total, however 33 or even more players enter, so there is not enough arena for everyone.

See if the map that this error happens has support for how many arenas, that solved for me.

I removed all maps that didn't have support for 16 arenas, and it didn't happen anymore.

**Comment by iGreen123** [comment]
> I've been watching this error, from what I've seen it happens on maps that don't have support for so many players / arenas.
> 
> That is, your server is 32 slots, you put a map for 16 arenas / 32 players in total, however 33 or even more players enter, so there is not enough arena for everyone.
> 
> See if the map that this error happens has support for how many arenas, that solved for me.
> 
> I removed all maps that didn't have support for 16 arenas, and it didn't happen anymore.

this is the list of my maps

"am_alley_v1" ""
"am_arena_c4" ""
"am_aztec2" ""
"am_aztec2015" ""
"am_aztec_arena" ""
"am_aztec_v6" ""
"am_bananag"aming_gbg" ""
"am_basement" ""
"am_basement_2019_v2" ""
"am_breakout" ""
"am_caribbean" ""
"am_castaway" ""
"am_construction_site" ""
"am_courtyard" ""
"am_crashz_dust_v3" ""
"am_cubes" ""
"am_d2_yard" ""
"am_dd2_short_dolnma" ""
"am_desert_64" ""
"am_desert_v2" ""
"am_drought" ""
"am_dust2" ""
"am_dust2014" ""
"am_dust2_cat" ""
"am_dust2_long" ""
"am_dust_arena_v2" ""
"am_dust_fixed" ""
"am_dust_v6" ""
"am_dzi" ""
"am_exhibit_fixed" ""
"am_graffiti" ""
"am_grass2" ""
"am_grass2_lego_wild" ""
"am_inferno_middle_dolnma" ""
"am_inferno_v2" ""
"am_killdepot_fix" ""
"am_lanii_wild" ""
"am_loot_fix" ""
"am_map1v1-64" ""
"am_market" ""
"am_mefix_64" ""
"am_memap_gg" ""
"am_minecraft_v3" ""
"am_mirage_mid_v0" ""
"am_multi_v6" ""
"am_must2" ""
"am_must2014" ""
"am_must2014_c4" ""
"am_nuke" ""
"am_nuke_hd64_22hd" ""
"am_nuke_ramp" ""
"am_offices" ""
"am_plain2" ""
"am_ramps_lego" ""
"am_redline_v2" ""
"am_rob_a" ""
"am_sandtunnel" ""
"am_sewage" ""
"am_skip" ""
"am_snow_cbg" ""
"am_snowfall_v3" ""
"am_texture2" ""
"am_texture2014" ""
"am_th_leeds" ""
"am_towers2" ""
"am_trainyard" ""
"am_underground" ""
"am_warehouse2" ""
"am_warehouse3" ""
"am_water2014" ""
"am_water_v6" ""
"am_xelougrass" ""
"am_yard_fixed" ""

**Comment by crashzk** [comment]
I believe it is easier if you check which map this problem occurs, then check if the map has support for 16 arenas.

**Comment by iGreen123** [comment]
> I believe it is easier if you check which map this problem occurs, then check if the map has support for 16 arenas.

ok thanks bro

**Comment by splewis** [comment]
I've added a warning that will be logged when there aren't enough arenas now.

When in doubt, you can run the `multi1v1_spawninfo` command in console to list the number of arenas on a map.
