### ISSUE TITLE
Client crashes on map changes

### ISSUE THREAD

**Issue by nuxcodex** [splewis/csgo-multi-1v1#221]
Hey I got some problems the first one is that me and some of my players crash on map change so we need to start csgo everytime it have changes map. The second problem I have is that it change maps 2 times when we vote for a map it change to a random map and after that it change to the map we voted for

**Comment by splewis** [comment]
>  some of my players crash on map change

Have you tested to see if the multi1v1 plugin is actually why? You should try changing to a map that causes it without multi1v1 enabled, or changing to a 'standard' map with multi1v1 enabled and see what happens.

>  The second problem I have is that it change maps 2 times when we vote for a map it change to a random map and after that it change to the map we voted for

I can't help with that, that's totally unrelated to the multi1v1 plugin.

**Comment by splewis** [comment]
Closing, not enough useful followup info here.
