### ISSUE TITLE
Map change does not work correctly

### ISSUE THREAD

**Issue by paulocrash** [splewis/csgo-multi-1v1#222]
### Expected behavior
Switch to the map you chose in the poll.

### Actual behavior
I use the `mapchooser.smx` plugin on my server to have map polls to choose the next map.

The voting appears normally, the players vote and choose the map, all right, but there are moments when the server changes to a standard CSGO map, `de_dust2` in the case, always for that.

### Steps to reproduce
Install Multi1v1 on the server.

I in the case I have the server configured with the steam workshop maps, I have a own collection, use it for the polls.

- Plugin version: CS:GO Multi1v1 (1.1.9) by splewis
- Sourcemod version: 1.9.0.6275

[errors_20190210.log](https://github.com/splewis/csgo-multi-1v1/files/2848472/errors_20190210.log)

**Comment by splewis** [comment]
I see no reason to think this is releated to multi1v1. It doesn't affect how your server changes maps at all.

>### Steps to reproduce
> Install Multi1v1 on the server.

That doesn't reproduce this.

**Comment by borzaka** [comment]
You want to use the native voting in CS:GO, or a SourceMod plugin to do that? Both can't work.

Fist, try to disable the nextmap plugin, which can interfere with other map changing plugins.
Second; have you edited the maplists.cfg “mapchooser” section to fill up only with compatible `am_` maps?

Additional info for SourceMod map management plugins: [Map Management Plugins (SourceMod)](https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod))

This is my solution, and it's working;
- disable all map change related plugins: nextmap, mapchooser, randomcycle, etc.
- make/use a workshop collection with compatible `am_` maps and host it
- change `mp_endmatch_votenextmap` to `1` in the `game_cvars.cfg` and probably `mp_endmatch_votenextleveltime` to a higher number
- the native map end voting should work

But splewis is right: this is not related to multi-1v1 plugin.

**Comment by paulocrash** [comment]
Worked, thank you @borzaka
