### ISSUE TITLE
log error!!

### ISSUE THREAD

**Issue by Drmohammad11** [splewis/csgo-multi-1v1#226]
hi!
i used last version:

L 04/17/2019 - 00:13:40: SourceMod error session started
L 04/17/2019 - 00:13:40: Info (map "am_must2") (file "errors_20190417.log")
L 04/17/2019 - 00:13:40: Error log file session closed.
L 04/17/2019 - 00:41:30: SourceMod error session started
L 04/17/2019 - 00:41:30: Info (map "am_respcs_v1") (file "errors_20190417.log")
L 04/17/2019 - 00:41:30: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 04/17/2019 - 00:41:30: [SM] Blaming: multi1v1.smx
L 04/17/2019 - 00:41:30: [SM] Call stack trace:
L 04/17/2019 - 00:41:30: [SM]   [1] Line 865, multi1v1.sp::Event_OnPlayerDeath
L 04/17/2019 - 01:53:06: Error log file session closed.
L 04/17/2019 - 16:00:59: SourceMod error session started
L 04/17/2019 - 16:00:59: Info (map "am_anothernuke") (file "errors_20190417.log")
L 04/17/2019 - 16:00:59: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 04/17/2019 - 16:00:59: [SM] Blaming: multi1v1.smx
L 04/17/2019 - 16:00:59: [SM] Call stack trace:
L 04/17/2019 - 16:00:59: [SM]   [1] Line 865, multi1v1.sp::Event_OnPlayerDeath
L 04/17/2019 - 16:29:07: Error log file session closed.

**Comment by splewis** [comment]
Known issue: #210
