### ISSUE TITLE
 When the map changes, the game closes

### ISSUE THREAD

**Issue by lazhoroni** [splewis/csgo-multi-1v1#228]
L 05/04/2019 - 00:38:04: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 05/04/2019 - 00:38:04: [SM] Blaming: multi1v1.smx
L 05/04/2019 - 00:38:04: [SM] Call stack trace:
L 05/04/2019 - 00:38:04: [SM]   [1] Line 864, ./scripting/multi1v1.sp::Event_OnPlayerDeath

Every minute gives this error. Sometimes the game is closed when the map is changed. 
I am using version 1.1.9.

**Comment by splewis** [comment]
> L 05/04/2019 - 00:38:04: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 05/04/2019 - 00:38:04: [SM] Blaming: multi1v1.smx
L 05/04/2019 - 00:38:04: [SM] Call stack trace:
L 05/04/2019 - 00:38:04: [SM] [1] Line 864, ./scripting/multi1v1.sp::Event_OnPlayerDeath

See https://github.com/splewis/csgo-multi-1v1/issues/210. 

Your crashes are unrelated to the plugin: https://forums.alliedmods.net/showpost.php?p=2651812&postcount=41
