### ISSUE TITLE
Bugged language?

### ISSUE THREAD

**Issue by denaegte** [splewis/csgo-multi-1v1#236]
### Expected behavior
I translated your plugin to danish and expected it to work

### Actual behavior
It doesn't. I started translating just a few lines, but after I translated everything no text shows up. 
And your plugin stops working. I've tried translating your plugin 3 times and kento rankme mod 2 times. Same results every time...

### Steps to reproduce
Set your languange to Danish with a danish "da" translation.
I even tried to remove our æ ø and å characters from the translations, but nothing changes.

- Plugin version: 1.1.10-dev+210
- Sourcemod version: 1.9.0.6282
- Steps to reproduce (please be specific):
[multi1v1.phrases.txt](https://github.com/splewis/csgo-multi-1v1/files/3781202/multi1v1.phrases.txt)
Just put my translation in the a cs:go servers translation folder.
`
Hope it's fixable..
Kind regards!

**Comment by splewis** [comment]
You should only have the Danish phrases in that file, not the format and the English language lines. Example: https://github.com/splewis/csgo-multi-1v1/blob/master/translations/es/multi1v1.phrases.txt
