### ISSUE TITLE
scoreboard showing players in the wrong order

### ISSUE THREAD

**Issue by yhirsh112** [splewis/csgo-multi-1v1#242]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
the scoreboard shows players organized by the arena.

### Actual behavior
the scoreboard shows players organized by score.

### Steps to reproduce
not sure...maybe help me find out what determines the order of the scoreboard
Please note that "latest" is NOT a version! Run "sm plugins" in the console to find out the exact plugin version.

- Plugin version: 1.1.9
- Sourcemod version: SourceMod 1.10.0.6407
- Steps to reproduce (please be specific): help me to figure out how to change what decide the order

**Comment by splewis** [comment]
Update sourcemod (see https://github.com/splewis/csgo-multi-1v1/issues/240), or at least the gamedata.

**Comment by yhirsh112** [comment]
thank you very much.
