### ISSUE TITLE
General Questions and Possible error

### ISSUE THREAD

**Issue by QuzFlips** [splewis/csgo-multi-1v1#247]
I've been using a 1v1 Arena Maps collection and every map I check looks fine. Problem for me is when 1 map ends,it automatically gets started into Dust_2. Where and in which category I can stop it? And properly load into other Workshop maps?

**Comment by iNilo** [comment]
Not a bug in 1v1

Check out https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators

Make sure you have set host_workshop_collection
