### ISSUE TITLE
Errors from Event_OnPlayerDeath

### ISSUE THREAD

**Issue by dzagu** [splewis/csgo-multi-1v1#258]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Actual behavior

L 03/30/2020 - 20:49:25: [SM] Blaming: multi1v1.smx
L 03/30/2020 - 20:49:25: [SM] Call stack trace:
L 03/30/2020 - 20:49:25: [SM]   [1] Line 864, ./scripting/multi1v1.sp::Event_OnPlayerDeath

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: CS:GO Multi1v1" (1.1.9) 
- Sourcemod version: 1.10
- Steps to reproduce (please be specific):

**Comment by iNilo** [comment]
Would need more error log lines.

Could you keep an eye out for the full error log?

**Comment by iRonicro** [comment]
Have a look here https://github.com/splewis/csgo-multi-1v1/issues/210
