### ISSUE TITLE
Add a function that can changing to the map in your workshop collection. 

### ISSUE THREAD

**Issue by renziyao** [splewis/csgo-multi-1v1#268]
I find it hard to change a csgo to a workshop map. I tried `host_workshop_map` but it didn't work at all. So I'm wondering that could you please add a function that allow user to change map(like .map in your practice plugin)? Or just a tutorial about how to change to a workshop map.

**Comment by splewis** [comment]
Sorry, I don't think this is something that makes sense to add to this plugin. Mapcycle management isn't specific to this gamemode, or plugin. I'd suggest asking here for help on that: https://forums.alliedmods.net/forumdisplay.php?f=130
