### ISSUE TITLE
How to add new weapon type?

### ISSUE THREAD

**Issue by tydaytygx** [splewis/csgo-multi-1v1#271]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
add smgs heavy nades weapon types as choices for player

### Actual behavior
I add the smgs in config but it doesn't work
> multi1v1_weapons.cfg

```
"SMGS"
        {
                "weapon_mac10"
                {
                        "name"          "MAC10"
                        "team"          "T"
                }

                "weapon_ump45"
                {
                        "name"          "ump45"
                        "team"          "ANY"
                }

                "weapon_p90"
                {
                        "name"          "P90"
                        "team"          "ANY"
                }

                "weapon_mp5sd"
                {
                        "name"          "MPSD"
                        "team"          "ANY"
                }

                "weapon_mp9"
                {
                        "name"          "MP9"
                        "team"          "CT"
                }

                "weapon_mp7"
                {
                        "name"          "MP7"
                        "team"          "ANY"
                }

                "weapon_bizon"
                {
                        "name"          "BIZON"
                        "team"          "ANY"
                }
        }

```

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: 1.1.8
- Sourcemod version: SourceMod Version: 1.10.0.6458
- Steps to reproduce (please be specific): 
> Add more weapon type but still only have rifles and pistols in sm menu

**Comment by splewis** [comment]
The `weapons.cfg` file only lets you modify the weapons for the builtin rifle & pistol round types.

To add a SMG round type where you can pick preferred weapons, you'd have to write it from another plugin: https://github.com/splewis/csgo-multi-1v1#adding-round-types-via-another-plugin

**Comment by tydaytygx** [comment]
Thanks

> The `weapons.cfg` file only lets you modify the weapons for the builtin rifle & pistol round types.
> 
> To add a SMG round type where you can pick preferred weapons, you'd have to write it from another plugin: https://github.com/splewis/csgo-multi-1v1#adding-round-types-via-another-plugin

Thanks :)
