### ISSUE TITLE
HUD pop ups doesn't have proper color & size.

### ISSUE THREAD

**Issue by Atlas7005** [splewis/csgo-multi-1v1#273]
### Expected behavior
Show text on hud in color & specified font options.

### Actual behavior
Displays XML or HTML looking code like "<font size='blah'..."

### Steps to reproduce

M1v1 v1.1.9
Sourcemod v1.10.0.6494
I legit have no idea why this is happening, no steps to reproduce. It happens when a round starts and a hud msg with opponent info pops up.

**Comment by walliski** [comment]
https://github.com/Franc1sco/FixHintColorMessages might help
