### ISSUE TITLE
Cannot enter in a TEAM , latest csgo update

### ISSUE THREAD

**Issue by duncosta** [splewis/csgo-multi-1v1#275]
12/04/2020 - 01:29:01: [SM] Exception reported: Failed to lookup TerminateRound signature.
12/04/2020 - 01:29:01: [SM] Blaming: multi1v1.smx
12/04/2020 - 01:29:01: [SM] Call stack trace:
12/04/2020 - 01:29:01: [SM][0] CS_TerminateRound
12/04/2020 - 01:29:01: [SM][1] Line 1171, ./scripting/multi1v1.sp::Timer_CheckRoundComplete

- Plugin version: "CS:GO Multi1v1" (1.1.9) by splewis
- Sourcemod version: 1.10.0.6455

**Comment by crashzk** [comment]
+1

**Comment by splewis** [comment]
Wait for a csgo update: https://github.com/splewis/csgo-pug-setup/wiki/Frequently-Asked-Questions#issues-after-a-csgo-update-aka-help-a-csgo-update-broke-the-mod
