### ISSUE TITLE
can not load the plugins on linux

### ISSUE THREAD

**Issue by g90130** [splewis/csgo-multi-1v1#277]
it's running on the latest version of the csgo and it reported an error
system:Centos 7.3 X64
error reported:

Server waking up from hibernation
L 12/05/2020 - 22:27:28: [UPDATER] Successfully updated gamedata file "sm-cstrike.games/game.csgo.txt"
L 12/05/2020 - 22:27:28: [UPDATER] SourceMod has been updated, please reload it or restart your server.
PutClientInServer: no info_player_start on level
ConVarRef sv_voice_proximity_minvolume doesn't point to an existing ConVar
L 12/05/2020 - 22:27:40: [SM] Exception reported: Failed to lookup TerminateRound signature.
L 12/05/2020 - 22:27:40: [SM] Blaming: multi1v1.smx
L 12/05/2020 - 22:27:40: [SM] Call stack trace:
L 12/05/2020 - 22:27:40: [SM]   [0] CS_TerminateRound
L 12/05/2020 - 22:27:40: [SM]   [1] Line 1171, ./scripting/multi1v1.sp::Timer_CheckRoundComplete
Msg from 118.115.10.28:27005: CCLCMsg_CmdKeyValues rejected by msg bind (55 bytes)

**Comment by splewis** [comment]
Update your sourcemod (or restart your server, so the gamedata is automatically updated). See #275
