### ISSUE TITLE
adding new weapons to list allows bots to join and blocking players?

### ISSUE THREAD

**Issue by mrshydk** [splewis/csgo-multi-1v1#280]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
use all weapons

### Actual behavior
no one can join the game. Bots fills the game and even after bot_kick you still cant join a team

### Steps to reproduce
adding all and even just some new weapons to server

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: 1.1.5 
- Sourcemod version: 1.10
- Steps to reproduce (please be specific):

**Comment by pedrotski** [comment]
You need to check your game gamemode config file for these lines (whatever one you are using)

bot_quota 0
bot_quota_mode normal

Be aware sometimes bots will randomly join, so you can use an enforcer plugin such as this one: https://forums.alliedmods.net/showthread.php?t=237004

**Comment by mrshydk** [comment]
done what you said. the bot problem is now solved but still cant join any teams

**Comment by splewis** [comment]
> Steps to reproduce (please be specific):

Can you provide info? You said you added weapons? What's in he config file? Have you checked for any error logs in `addons/sourcemod/logs`?
