### ISSUE TITLE
Custom Rounds Not Working

### ISSUE THREAD

**Issue by Jadowo** [splewis/csgo-multi-1v1#281]
I've tried to enable the scout rounds to test them 
I'm not sure if i've missed something but all i've changed is the 0 to a 1
I've also added some other ones that also don't work
I have pasted what I have down below
- Plugin version: 1.1.9
- Sourcemod version: 1.10
- Steps to reproduce (please be specific):
 the players will get the rifle or pistol they have selected.

```
"CustomRoundTypes"
{
    "scout"
    {
        "name"      "Scout"
        "ranked"        "1"
        "ratingFieldName"       ""
        "optional"      "1"
        "enabled"       "1"
        "armor"     "1"
        "helmet"        "1"
        "weapons"
        {
            "weapon_knife"      ""
            "weapon_ssg08"      ""
        }
    }
    "bumpy"
    {
        "name"      "Cowboys"
        "ranked"        "1"
        "ratingFieldName"       ""
        "optional"      "1"
        "enabled"       "1"
        "armor"     "1"x
        "helmet"        "1"
        "weapons"
        {
            "weapon_knife"      ""
            "weapon_revolver"      ""
        }
    }
    "mag7"
    {
        "name"      "Mag7Sluts"
        "ranked"        "1"
        "ratingFieldName"       ""
        "optional"      "1"
        "enabled"       "1"
        "armor"     "1"
        "helmet"        "1"
        "weapons"
        {
            "weapon_knife"      ""
            "weapon_mag7"      ""
        }
    }

}
```

**Comment by splewis** [comment]
Have you checked error logs (``addons/sourcemod/logs``)?

There's a syntax error in the "bumpy" section:
```
        "armor"     "1"x
```

**Comment by Jadowo** [comment]
Yeah i noticed that too after i posted this. even when removing that error it still didn't work and only having the scout stuff didn't work either

**Comment by Jadowo** [comment]
I somehow managed to skip the first line of your reply on my first read. But yeah reading the logs there was an adminsmite translation file missing but that wasn't it. When I got on today it was working. Turns out I need to restart the server for it to take effect. Thank you!
