### ISSUE TITLE
How Enable Facing off?

### ISSUE THREAD

**Issue by potsepunof** [splewis/csgo-multi-1v1#285]
Help plz!
Working, print when opponent left.
When I have an opponent, no one message. 
Must 
"FacingOff"
	{
		"#format"	"{1:i},{2:N}"
		"en"		"You are in arena {GREEN}{1}{NORMAL}, facing off against {PURPLE}{2}{NORMAL}."
	}

**Comment by splewis** [comment]
Do you have any more information?
* plugin version?
*  any error logs in `addons/sourcemod/logs`?
* simple steps to reproduce
