### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Davvud** [splewis/csgo-multi-1v1#289]
Downloaded latest version from github.
Did absolutely nothing to the script just wanted to compile it as it is. I got this error:
SM version used for compilig : 1.11.0.6881

![image](https://user-images.githubusercontent.com/77155703/168378499-1dfec533-efbd-434d-a0d3-81fce093512d.png)

**Comment by Davvud** [comment]
Nvm I fixed it

**Comment by splewis** [comment]
See #287
