### ISSUE TITLE
Unable to compile latest version.

### ISSUE THREAD

**Issue by ErikOddur02** [splewis/csgo-multi-1v1#293]
Unable to compile.
Latest sourcemod version.
Latest plugin version.

//// multi1v1_flashbangs.sp
//
// multi1v1\generic.sp(261) : error 017: undefined symbol "Client_GetWeaponsOffset"
// multi1v1\generic.sp(264) : error 017: undefined symbol "MAX_WEAPONS"
// multi1v1\generic.sp(269) : error 017: undefined symbol "Weapon_IsValid"
// multi1v1\generic.sp(273) : error 017: undefined symbol "Entity_ClassNameMatches"
// multi1v1\generic.sp(274) : error 017: undefined symbol "Client_SetActiveWeapon"
// multi1v1\generic.sp(279) : error 017: undefined symbol "Client_SetWeaponPlayerAmmoEx"
// multi1v1\generic.sp(283) : error 017: undefined symbol "Entity_Kill"

//// multi1v1.sp
//
// multi1v1\spawns.sp(142) : error 101: fixed dimensions must be after the array name, not on the type
// multi1v1\spawns.sp(152) : error 101: fixed dimensions must be after the array name, not on the type
// multi1v1\spawns.sp(158) : error 101: fixed dimensions must be after the array name, not on the type

multi1v1_kniferounds.sp compiles.

**Comment by splewis** [comment]
> Latest sourcemod version.

See #287
