### ISSUE TITLE
When u dont check before release?

### ISSUE THREAD

**Issue by Quake1011** [splewis/csgo-multi-1v1#294]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// multi1v1.sp
//
// multi1v1\natives.sp(406) : error 100: function prototypes do not match
//
// 1 Error.
//
// Compilation Time: 1,12 sec
// ----------------------------------------

Press enter to exit ...

**406 | RoundTypeWeaponHandler weaponHandler = view_as\<RoundTypeWeaponHandler>\(GetNativeFunction(3));**

Latest SM
Latest PLUGIN

**Comment by splewis** [comment]
> Latest SM

See #287
