### ISSUE TITLE
Support for "3rd party weapons"

### ISSUE THREAD

**Issue by splewis** [splewis/csgo-multi-1v1#50]
e.g. what h3bus added to his deathmatch plugins with the cvar ``dm_weapons_allow_3rd_party``. This would let some of the custom-knife selection plugins work. 

Also see https://forums.alliedmods.net/showpost.php?p=2203238&postcount=333

**Comment by pim221** [comment]
Could you perhaps take another look at this :)?

**Comment by splewis** [comment]
I don't have the time or drive to get these things done, but if anyone else wants to there's a hint in this post that might help: https://forums.alliedmods.net/showpost.php?p=2258875&postcount=583

**Comment by splewis** [comment]
Since Valve disallows these modifications now, it's not particularity worth worrying about compatibility with them.
