### ISSUE TITLE
Config to enable guns menu when client reconnects

### ISSUE THREAD

**Issue by charleszlu** [splewis/csgo-multi-1v1#80]
There should be a cvar/cfg item to let the user reselect their guns every time they reconnect to the server. Something like: sm_multi1v1_guns_menu_reconnect "0/1".

**Comment by splewis** [comment]
Done by https://github.com/splewis/csgo-multi-1v1/commit/7f43ac7357dbc258fb52b1c04e94eed2eb80c097
