### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by bocian22xd** [splewis/csgo-multi-1v1#83]
I've problem with ranking.

I complete connection with database etc but when I'm typing !rank I see only this:

http://scr.hu/3hy4/m5529

When I'm typing !stats:

http://scr.hu/3hy4/0v5s6
and when I'm entering a nickname:
http://scr.hu/3hy4/5uvco

I saw server who's using this ranking "ingame", somethink like when you typing !admin

And !top/!top15 don't working.

**Comment by bocian22xd** [comment]
I've create new database, now even when I'm changing map, I'm not in ranking. Database is clear, and !rank saying that there is no player with that name. Im green with that so please help me

**Comment by BrutalCSkakan** [comment]
Both your php config and the gamefiles needs to be connected to the database. I could guess that you've only connected one of them

**Comment by bocian22xd** [comment]
config.inc.php is complete

multi1v1.cfg:
sm_multi1v1_stats_url "http://arenaangelskill.gameclan.pl/redirect.php?id={ID}&server_id={SERVER}"

and databases.cfg is complete

**Comment by splewis** [comment]
What version of the plugin and the /web interface are you using?


> ps. Why installation is so confusing. Everything is messed up after throughout.Should be one description, everything, and how in turn.

That's because you're using a web interface that doesn't have a stable release yet.

**Comment by bocian22xd** [comment]
Hmm. I left server for few minutes. And now, database is working fine, everythink is working fine, there is no 999 players in rank with name Bocian. There is only one thing:
When I'm typing !rank does not appear immediately, my ranking but I need to search in right top corner. 

This is my script:
http://arenaangelskill.gameclan.pl/redirect.php?id={ID}&server_id=0

**Comment by splewis** [comment]
I can't help unless I know what plugin versions you're using.

**Comment by bocian22xd** [comment]
Latest

**Comment by bocian22xd** [comment]
I install it today so 0.5.2

**Comment by splewis** [comment]
Then you're using the last plugin release but pulled the web interface from the git repo, which expects that the plugin is updated as well. That doesn't work.

You can either
- update the plugin
- downgrade the web interface (probably back to this point: https://github.com/splewis/csgo-multi-1v1/tree/bfe9de41ff15802373b37d947839d2e28de633ce/web)

**Comment by bocian22xd** [comment]
I don't want to do somethink with plugin becouse I work much with this plugins, so I will try to downgrade web.

**Comment by bocian22xd** [comment]
Ok, everything beautiful. Last question, how to add !top15 to http://arenaangelskill.gameclan.pl/

**Comment by splewis** [comment]
You could probably use this plugin to do that: https://forums.alliedmods.net/showthread.php?t=244075

**Comment by bocian22xd** [comment]
Everythink smells good. 1 question:

My friend create me a plugin for only hs preferences, but we can't compile it. I use sourcemod 1.6 and 1.7 compiler linux and windows, smlib 1.10 and 1.11 and always there are errors.
http://wklej.org/id/1600329/

What we doing wrong?

**Comment by splewis** [comment]
I can't help if I don't know what the errors are. You probably need an updated version of smlib though.

**Comment by bocian22xd** [comment]
"edit2: that plugin is also silly since it doesn't give the players any weapons"

weapons will be immediately given preference, so I infer but niewiem thoroughly.

**Comment by bocian22xd** [comment]
When I delete smlib prom plugin:

http://wklej.org/id/1600505/

**Comment by bocian22xd** [comment]
You know your plugin, can you create this preference for me? 

I would be very grateful. Really.

**Comment by splewis** [comment]
Line 40
```
	new client = GetClientOfUserId(GetEventInt(event, "userid"));
```

you probably should name that victim since that's the variable being used below.


If you want it to give the rifle the player chose, you should change:
```
public void HSHandler(int client) {
	onlyhs[client]=true;
}

```

to

```
public void HSHandler(int client) {
	char rifle[WEAPON_NAME_LENGTH];
	Multi1v1_GetRifleChoice(client, rifle);
	GivePlayerItem(client, rifle);
	onlyhs[client]=true;
}
```

**Comment by bocian22xd** [comment]
Script:
http://wklej.org/id/1601296/
Error:
http://wklej.org/id/1601299/

I don't know what to do ;/
My friend tell me that this is on new syntex

**Comment by Bara20** [comment]
http://wklej.org/id/1601296/
Line 44: change 'client' to 'victim'
Line 51: same here.

**Comment by bocian22xd** [comment]
http://wklej.org/id/1601314/

;/

**Comment by splewis** [comment]
My bad, to use ``GivePlayerItem`` you need to add

``#include <sdktools>``

And you still need to find the values for g_iHealth and g_Armor. I don't recall exactly what you need to do to get those.

**Comment by bocian22xd** [comment]
Left only this:
http://wklej.org/id/1601339/

I do not write plugins, do not know much about it too much, My friend wrote this.

**Comment by Bara20** [comment]
Replace "g_iHealth" with "FindSendPropOffs("CBasePlayer", "m_iHealth")" or use SetEntityHealth ( https://sm.alliedmods.net/api/index.php?fastload=show&id=819& ).
and for armor:
Replace g_Armor with "FindSendPropOffs("CCSPlayer", "m_ArmorValue")"

**Comment by bocian22xd** [comment]
Holy shit, it works ;p
Now only problem with hitgroup but its compiled, i will test it now
http://wklej.org/id/1601401/

**Comment by bocian22xd** [comment]
:O How to add this to menu to choose that you want only hs or not. Somethink like Give player flashbans?

**Comment by Bara20** [comment]
I think this is HeadShot Only or am I wrong? Then you must check the hitgroup.
http://www.eventscripts.com/images/a/ae/Css_hit_group.jpg

**Comment by bocian22xd** [comment]
Yes this plugin should be displayed after Give Player Flashbang? Somethink like that Allow round only headshot? and when you check yes, and other side have yes, you should have round only hs

**Comment by Bara20** [comment]
Take a look on Multi1v1_OnGunsMenuDone.
https://github.com/splewis/csgo-multi-1v1/blob/master/scripting/multi1v1_flashbangs.sp

**Comment by splewis** [comment]
> Yes this plugin should be displayed after Give Player Flashbang? Somethink like that Allow round only headshot? and when you check yes, and other side have yes, you should have round only hs

Then it's not an actual round type and you should do what bara suggested and follow the flashbang example.

You'd probably also want to print to chat to tell players it's a headshot only round or it would get very confusing.

**Comment by bocian22xd** [comment]
Actually sp
http://wklej.org/id/1601426/

just tell me if there is the possibility of the creation?

**Comment by Bara20** [comment]
Now you added a handler but no menu.

**Comment by bocian22xd** [comment]
It not added to the menu
http://wklej.org/id/1601576/

I beg you, buddy, can you do for me? I can give you some skin; p

**Comment by bocian22xd** [comment]
Can anybody do this for me?

**Comment by splewis** [comment]
Asking people to write plugins for you isn't the purpose of this section.

Anyway, what you have makes no sense still. Are you trying to create a full-new round type (e.g. rifle/awp/pistol) or just add an opt-in behavior to all of the round types (the way the flashbangs work)?

**Comment by bocian22xd** [comment]
Listem to me.

I want to add somethink like flashbang, not awp becouse not always when 2 guys have awp is awp round, but when both have flashbank to yes, they have flashbang. So I want to create round:

Both have "Only HS round?" YES
Then round on that arena is only hs, 
When only 1 have only hs, its normal like always. You got it?

**Comment by splewis** [comment]
You can do it 2 ways. 

- By adding a new round type calling ``Multi1v1_AddRoundType`` with a clever handler to give the pistol/rifle/whatever 
- By creating a menu in ``Multi1v1_OnGunsMenuDone``, but this will conflict with the flashbang plugin if you're using that

You're doing some confusing combination of both right now.

**Comment by bocian22xd** [comment]
I have to wait for a friend to write a plugin me all over again, and my question is, how to change the start time of the next round? I would like to put roundsounds into server, but round for changing rapidly and there is no sound

**Comment by splewis** [comment]
mp_round_restart_delay in cfg/sourcemod/multi1v1/game_cvars.cfg

**Comment by bocian22xd** [comment]
I've create test-plugin to check whether it will be showed the menu.
I copied the flashbang plugin, I changed everything, looks like this:
http://wklej.org/id/1604798/

When compiling:
http://wklej.org/id/1604799/

**Comment by bocian22xd** [comment]
"mp_round_restart_delay in cfg/sourcemod/multi1v1/game_cvars.cfg"

Doesn't work

**Comment by splewis** [comment]
mp_round_restart_delay changes the delay between round end and round start. You either didn't describe what you wanted correctly or didn't set the cvar correctly.

You would need to update smlib to fix those errors.

**Comment by bocian22xd** [comment]
mp_round_restart_delay 7 in game_cvars.cfg

**Comment by bocian22xd** [comment]
I have latest smlib (beta)

**Comment by bocian22xd** [comment]
After some time, the server inspection, I came to culpable negligence on my part. I use SourceMod 1.7, while the server is loaded plugin dev and superimposed 0.5.2. I am currently in the phase of moving server 1.7 SourceMod plugin dev. Probably because errors and very sorry if it's only by all the fuss. Like everything I do, I will tell you.
