### ISSUE TITLE
Round

### ISSUE THREAD

**Issue by bocian22xd** [splewis/csgo-multi-1v1#86]
Cvar: mp_round_restart_delay 8   doesn't work good. Sometimes round appears immediately, so I can't add round sounds couse it's annoying to head music only 1 second.

How to fix this ^^

**Comment by splewis** [comment]
Should be fixed now, so setting mp_round_restart_delay should actually have the correct effect.

**Comment by bocian22xd** [comment]
I don't get you. What should I do?
