### ISSUE TITLE
HS round deleting flashbangs

### ISSUE THREAD

**Issue by bocian22xd** [splewis/csgo-multi-1v1#88]
Finally we wrote a plugin that works round adds to hs if two people have it set. However, it is a problem that removes choice "Give players flashbang?" and uses its cookies, or how someone had turned on fleshbangs, is automatically included in the HS Only in rounds.

What exactly do I want ?:
-Przywrócić Choice Flesh
-To Use the new plugin cookies (I have no idea why it does not)

Plugin: http://wklej.org/id/1606933/
SM 1.7
MM: 1.11
Multi: 1.0.0 (latest DEV)

**Comment by bocian22xd** [comment]
We did well in the form of preference round:
http://wklej.org/id/1606161/

You could check if there are any errors, shortcomings, and that it was only assault rifles and pistols, because it is not likely awp fit. You know your plugin, its events, hooks, we do not and that is why we ask you, and ask for help.

**Comment by splewis** [comment]
Your first plugin confuses me since it calls everything a "fishbang" but seems to do headshot only rounds.

You're second plugin doesn't give players any weapons in ``CzekoladaHandler``, so it's pretty pointless.

**Comment by bocian22xd** [comment]
It's just name, my friend told me them I'm looks like a fish :D

We doing this plugin right now. Believe me it is difficult to write a plugin to the plugin you did not know.

**Comment by bocian22xd** [comment]
http://wklej.org/id/1607750/

Almost finish.

We need native to get the id players in the same arena.

**Comment by splewis** [comment]
I'm not sure why you need that, but there is ``Multi1v1_GetArenaNumber``

https://github.com/splewis/csgo-multi-1v1/blob/master/scripting/include/multi1v1.inc#L198

The ``Multi1v1_OnRoundTypeDecided`` forward might also help.

**Comment by bocian22xd** [comment]
We need it to print message to clients that this is Only HS round

**Comment by splewis** [comment]
```
public void Multi1v1_OnRoundTypeDecided(int arena, int player1, int player2, int& roundType) {
	if (roundType == Multi1v1_GetRoundTypeIndex("headshot")) {
		Multi1v1_Message(player1, "This is a headshot only round");
		Multi1v1_Message(player2, "This is a headshot only round");
	}
}
```

where the "headshot" is whatever name got passed when doing the ``Multi1v1_AddRoundType`` call.

**Comment by bocian22xd** [comment]
I could be wrong, but I think your update url does not work
https://dl.dropboxusercontent.com/u/76035852/multi1v1-v1.x/csgo-multi-1v1.txt

**Comment by bocian22xd** [comment]
http://wklej.org/id/1608271/

Onlyhs and message working, but when we enable everythink and on chat is: 
This is headshot only round
There is no onlyhs
When we disable and only hs enable, onlyhs working.
When is onlyhs, we have only refile, no pistol and no knife.

**Comment by splewis** [comment]
> Sometimes plugin says This is headshoot round only, but it isn't.

That's because these lines are blocking a headshot round:
```
	new String:server_port[20];
	new String:server_port2[20];
	GetCookieStringByName(attacker, "multi1v1_preference", server_port, sizeof(server_port));
	GetCookieStringByName(victim, "multi1v1_preference", server_port2, sizeof(server_port2));
	Multi1v1_GetRoundTypeIndex(server_port);
	Multi1v1_GetRoundTypeIndex(server_port2);
```

Those shouldn't be there at all, same with the ``StrEqual(server_port, "onlyhs")&&StrEqual(server_port2, "onlyhs")``

> And sometimes plugin don't says Only hs round but it is only hs.

Because you're never resetting the hs boolean variable.

It might be simpler just to do
```
public void Multi1v1_OnRoundTypeDecided(int arena, int player1, int player2, int& roundType) {
    if (roundType == Multi1v1_GetRoundTypeIndex("onlyhs")) {
        Multi1v1_Message(player1, "\x02This is a headshot only round");
        Multi1v1_Message(player2, "\x02This is a headshot only round");
        hs[player1] = true;
        hs[player2] = true;
    } else {
        hs[player1] = false;
        hs[player2] = false;
    }
}
```

> And when is only hs round (only refile rounds) we have only refile, without knife and pistol.

Then give the player a knife and pistol.

**Comment by bocian22xd** [comment]
Plugin works very well right now, there is only 1 issue.
http://wklej.org/id/1608936/

When I'm shooting to someone, I'm adding him hp.

**Comment by bocian22xd** [comment]
My friend came to the conclusion that there is nothing to play around with it all and wrote a plugin in this way, using SDKHooks
http://wklej.org/id/1609087/
It all when it comes to this type of round (I hope)

I still remains the question of how to delete a pistol from AWP rounds

**Comment by splewis** [comment]
sm_multi1v1_pistol_behavior 3
sm_multi1v1_default_pistol ""
