### ISSUE TITLE
Match MPV

### ISSUE THREAD

**Issue by bocian22xd** [splewis/csgo-multi-1v1#89]
I have a question.

Do you like the end of the round is displayed:
"PLAYER had the most wins in the arena 1"

Whether it's somewhere I save?

If there is a possibility to save it if the server has more than 6 people?

**Comment by splewis** [comment]
I'm not going to add anything to save that, but the ``Multi1v1_GetRoundsAtArena1`` native will let another plugin do whatever it wants with that data.
