### ISSUE TITLE
Web interface requires PHP with CURL

### ISSUE THREAD

**Issue by erikxcore** [splewis/csgo-multi-1v1#94]
Noticed it wasn't listed as a requirement on the web branch; any who, I had to recompile my PHP build with CURL support for the stats page to work per player. Not a big deal, but if anyone else was getting blank pages/could not find player stats when clicking directly on player names or searching (top 15 worked fine) that's probably why - I set display errors on and error reporting E_ALL to figure this out in any case.

**Comment by supimfuzzy** [comment]
I had to use cURL because get_file_contents() was too slow and holding up the page for 5> seconds.

**Comment by nguyenbaodanh** [comment]
how to fix ? I have this blank page on players too :(

**Comment by supimfuzzy** [comment]
The player stats not showing up was due to serverid being always set to 0. I've made a pull request and you can download a clone after splewis merges it.
