### ISSUE TITLE
Plugin multi1v1.smx failed to load: Native "ReadPackFunction" was not found.

### ISSUE THREAD

**Issue by bonoxx** [splewis/csgo-multi-1v1#96]
Getting this error when trying to load the plugin. I'm failry new to running a cs go dedicated server. I'm however able to run a deathmatch goes advanced server. On Windows. any ideas?

**Comment by Bara20** [comment]
You need SourceMod 1.7+

**Comment by bonoxx** [comment]
Thanks Bara20 , Indeed something went wrong with my upgrade of sourcemod, I upgraded again and it worked.
