### ISSUE TITLE
problem with mysql

### ISSUE THREAD

**Issue by Joob** [splewis/csgo-multi-1v1#97]
Why doesn't connect to the mysql (database) ? I put the correct info etc.. ip, user, pass, database, etc.. it's ok..

But give me this error
-----
Could not connect: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 111

Regards,
Joob

**Comment by splewis** [comment]
It's not the fault of the plugin. Is the MySQL server on a different machine? If so, make sure it's configured to actually accept remote connections (which it doesn't, by default)

**Comment by Joob** [comment]
Yes, I know this is not a problem of the plugin.. oh nice ;) good tip.. I'll check this.. !

**Comment by Joob** [comment]
I resolved the problem ;)
Thanks..

Regards
