### ISSUE TITLE
command rank/top

### ISSUE THREAD

**Issue by Joob** [splewis/csgo-multi-1v1#98]
Hello,

The command on server.. (rank/top15).. doesn't work.. 

Regards

**Comment by splewis** [comment]
You have to give more information. Are you using the stock web interface? the online_stats_viewer plugin?

**Comment by Joob** [comment]
Yes, correct..
I use this mode...

sm_multi1v1_stats_url "http://site.com/test/redirect.php?id={USER}"
sm_multi1v1_top_url "http://site.com/test"

and don't give me the top15 (geral) or user..

**Comment by Joob** [comment]
Wait.. now.. "stats_url" it works..
but the "top_url" still doesn't work..

**Comment by splewis** [comment]
You should be using the redirect page for both urls.

**Comment by Joob** [comment]
Oh oky.. I'll create a motd.. ;)
Tks .. :)
